quickstart-templates/rhel-templates.json
s2i-java/Dockerfile
s2i-java/README.md
s2i-java/java-container-options
s2i-java/jolokia-opts
s2i-java/jolokia.properties
s2i-java/run-env.sh
s2i-java/run-java.sh
s2i-java/s2i/assemble
s2i-java/s2i/run
s2i-java/s2i/s2i-setup
s2i-java/s2i/save-artifacts
s2i-java/s2i/usage

Adds RHEL based Java S2I builder
Login to an OpenShift environment and create a new or use an existing project
Build the S2I image
`oc new-build https://github.com/sabre1041/containers-quickstarts#s2i-java --docker-image=registry.access.redhat.com/rhel:7.2 --context-dir=s2i-java --name=s2i-java --strategy=docker`
Once the build completes successfully, deploy a sample application
`oc new-app s2i-java~https://github.com/christian-posta/springboot-f8-demo --name=s2i-java-app`
Verify the build completes successfully and the application is deployed.
Expose the *s2i-java-app* so that is externally accessible
`oc expose svc s2i-java-app`
Locate the hostname of the route that was created
`oc get route s2i-java-app --template='{{ .spec.host }}'`
Navigate to the following URL to confirm …

RHEL based Java S2I builder

---

jenkins-slaves/jenkins-slave-image-mgmt/Dockerfile
jenkins-slaves/jenkins-slave-image-mgmt/README.md
jenkins-slaves/jenkins-slave-image-mgmt/etc/policy.json
jenkins-slaves/templates/jenkins-slave-image-mgmt-template.json

Adds a Jenkins slave image to perform image management (promotions using [skopeo](https://github.com/projectatomic/skopeo/))
A template has been provided to automate the building process
Execute the following from within the *jenkins-slaves/templates* folder to instantiate the template to create the requisite imagestreams and buildconfig
```
oc process -v=SOURCE_REPOSITORY_URL=https://github.com/sabre1041/containers-quickstarts.git,SOURCE_REPOSITORY_REF=jenkins-slave-image-mgmt -f jenkins-slave-image-mgmt-template.json | oc create -f-
```
cc: @redhat-cop/containerize-it @etsauer

Image management jenkins slave

---

jenkins-slaves/jenkins-slave-ansible-stacks/Dockerfile
jenkins-slaves/jenkins-slave-ansible-stacks/README.md
jenkins-slaves/templates/jenkins-slave-ansible-stacks-template.json

This pull request adds a jenkins slave image for using ansible-stacks from a jenkins slave. This came out of work with a recent engagement where we provisioned projects and resources in OpenShift.
See the README.md for instantiating the template to build the image. For example:
oc process -f templates/jenkins-slave-ansible-stacks-template.json \
-v SOURCE_REPOSITORY_URL=https://github.com/jkupferer/containers-quickstarts.git \
-v SOURCE_REPOSITORY_REF=master \
-v ANSIBLE_YUM_REPO=rhel-7-server-ose-3.3-rpms | oc create -f -
Next run the image in Jenkins with sample code to test. The jenkins service account will need self-provisioner role for the given example to succeed.

Add jenkins-slave-ansible-stacks

---

s2i-java/README.md

Adds deprecation notice to s2i-java image as supported image is now available
N/A

Added deprecated notice to s2i-java image

---

jenkins-slaves/jenkins-slave-image-mgmt/Dockerfile

Provides a workaround to an [issue](https://bugzilla.redhat.com/show_bug.cgi?id=1479388) when using `yum-config-manager` in a RHEL 7.4 base image
Follow the instructions in the README. Change the following template parameters:
* SOURCE_REPOSITORY_URL=https://github.com/sabre1041/containers-quickstarts.git
* SOURCE_REPOSITORY_REF=yum-install-fix
#42 

Fix issue with RHEL 7.4 and yum-config-manager

---

zookeeper/Dockerfile

Remove the added `zookeeper` user from the zookeeper image as it shouldn't be needed.
This helped solve an issue for @jihed where the container would run as `zookeeper` user.
Follow instructions in [README.md](README.md)

Remove zookeeper user from image

---

jenkins-slaves/jenkins-slave-golang/Dockerfile.rhel7
jenkins-slaves/templates/jenkins-slave-generic-template.yml

Add separate Dockerfile for RHEL 7
`oc process -f jenkins-slaves/templates/jenkins-slave-generic-template.yml -p NAME=jenkins-slave-golang -p SOURCE_CONTEXT_DIR=jenkins-slaves/jenkins-slave-golang | oc create -f -`

Add separate Dockerfile for RHEL, fixes #87

---

tool-box/README.md

Since this was moved from rht-labs/labs-ci-cd to redhat-cop/containers-quickstarts, the README was out of date.
Run the commands provided in the README.

Updating tool-box README to reflect moving repos

---

gitlab-ce/inventory/hosts

Fixing the gitlab-ce inventory to have the `ansible_connection=local` setting so it can be run on newer versions of Ansible.
Had someone run the steps in the README for gitlab-ce and they were getting the 'failed to connect to localhost' issue. This resolves it.
Run the steps from the gitlab-ce README.

Adding ansible_connection setting for localhost for gitlab-ce

---

gitlab-ce/files/templates/gitlab-ssl.yml

Currently the template assumes gitlab will be deployed in the gitlab namespace.
Run the steps in the README.

Updating gitlab template to have namespace parameter

---

tool-box/Dockerfile
tool-box/README.md
tool-box/root/usr/local/bin/run

Updating the tool-box image so that it does not need to be run as a daemon
Follow the updated README instructions to exercise the image. Since it is not yet pushed to quay, you will need to build it. To test the OpenShift build, use the following:
```
oc new-build https://github.com/etsauer/containers-quickstarts#runonce-toolbox --name=tool-box --context-dir=tool-box
```

Runonce toolbox

---

jenkins-slaves/jenkins-slave-ansible/Dockerfile

Updating the Dockerfile for `jenkins-slave-ansible` to lock it on a `2.5.x` version of Ansible
1. Create a new OCP project:
` > oc new-project my-test`
2. Use the template to instantiate the build of the image:
`> oc process -f jenkins-slaves/templates/jenkins-slave-generic-template.yml -p 'SOURCE_REPOSITORY_URL=https://github.com/oybed/containers-quickstarts.git' -p 'SOURCE_CONTEXT_DIR=jenkins-slaves/jenkins-slave-ansible' -p 'BUILDER_IMAGE_NAME=registry.access.redhat.com/openshift3/jenkins-slave-base-rhel7:latest' -p 'NAME=jenkins-slave-ansible' -p 'SOURCE_REPOSITORY_REF=jenkins-slave-ansible' -p 'DOCKERFILE_PATH=Dockerfile' | oc apply -f -`
3. Validate that the build succeeded and that an new image was created
`> oc get builds`
4. Validate that the ansible version in the image is …

Locking 'jenkins-slave-ansible' on 2.5.x of Ansible

---

jenkins-slaves/jenkins-slave-ansible/Dockerfile
jenkins-slaves/jenkins-slave-ansible/Dockerfile.rhel7

Add pip to Jenkins Ansible Slave
Follow steps in README, then command below
```
oc run ansible-slave -i -t --image=docker-registry.default.svc:5000/ansible-slave/jenkins-slave-ansible --command -- pip -V      
If you don't see a command prompt, try pressing enter.
pip 8.1.2 from /usr/lib/python2.7/site-packages (python 2.7)
```

Add pip to Jenkins Ansible Slave, fixes #128

---

jenkins-slaves/jenkins-slave-golang/Dockerfile

Adding `dep` into the golang build slave. There are numerous dependency managers for golang. Dep is the official experiment dependency manager. Opening this PR to decide if we want to include a dependency manager or require image builds downstream to incorporate the appropriate dependency manager.
docker build .

add dep into golang build slave

---

jenkins-slaves/jenkins-slave-npm/Dockerfile.rhel7

yum fails:
Error: Package: google-chrome-stable-70.0.3538.77-1.x86_64 (/google-chrome-stable_current_x86_64) Requires: liberation-fonts
(On RHEL)
docker build .

Added repository for missing dependency in new chrome

---

jenkins-slaves/jenkins-slave-image-mgmt/README.md

This fixes a reference from a .json file that doesn't exist to the appropriate .yml file.
resolves #146 
Doc fix. Verify example points to existing .yml file

Fix jenkins-slave-image-mgmt doc to reference .yml

---

README.md
jenkins-slaves/jenkins-slave-ansible/Dockerfile
jenkins-slaves/jenkins-slave-ansible/Dockerfile.rhel7
jenkins-slaves/jenkins-slave-ansible/README.md
jenkins-slaves/jenkins-slave-arachni/Dockerfile
jenkins-slaves/jenkins-slave-arachni/Dockerfile.rhel7
jenkins-slaves/jenkins-slave-golang/Dockerfile
jenkins-slaves/jenkins-slave-golang/Dockerfile.rhel7
jenkins-slaves/jenkins-slave-gradle/Dockerfile
jenkins-slaves/jenkins-slave-gradle/Dockerfile.rhel7
jenkins-slaves/jenkins-slave-image-mgmt/Dockerfile
jenkins-slaves/jenkins-slave-image-mgmt/README.md
jenkins-slaves/jenkins-slave-mongodb/Dockerfile
jenkins-slaves/jenkins-slave-mongodb/Dockerfile.rhel7
jenkins-slaves/jenkins-slave-mvn/Dockerfile
jenkins-slaves/jenkins-slave-mvn/README.md
jenkins-slaves/jenkins-slave-npm/Dockerfile
jenkins-slaves/jenkins-slave-npm/Dockerfile.rhel7
jenkins-slaves/jenkins-slave-npm/src/google-chrome.repo
jenkins-slaves/jenkins-slave-python/Dockerfile
jenkins-slaves/jenkins-slave-python/Dockerfile.rhel7
jenkins-slaves/jenkins-slave-ruby/Dockerfile
jenkins-slaves/templates/jenkins-slave-ansible-stacks-template.yml
jenkins-slaves/templates/jenkins-slave-generic-template.yml
jenkins-slaves/templates/jenkins-slave-image-mgmt-template.yml
jenkins-slaves/templates/jenkins-slave-ruby-template.yml

This PR will cover the Jenkins slave images to match the OCP release and solve some existing issues on resultant slaves like npm and others, where we have seen unexpected results when running 'latest' tag of the base images when a new major version is available and the 'latest' tag is moved in the Red Hat Container Catalog.
Build Jenkins slave images using instructions from the repository

Tie Jenkins slave images to match OCP release

---

jenkins-slaves/jenkins-slave-zap/README.md

When I started the docker container, it was not configured to run python scripts automagically. Adding '.py' to the invocation of the zap-baseline script fixed this. It should not negatively impact anyone.
After building the docker image, start it. Then run /zap/zap-baseline.py. You should see the help message.

Add '.py' to invocation of zap-baseline script.

---

jenkins-masters/hygieia-plugin/.openshift/templates/jenkins-s2i.yml
jenkins-masters/hygieia-plugin/configuration/init.groovy.d/configure-jenkins.groovy

Add a script to set the jenkins root URL to custom hygieia jenkins master
1. Run the applier playbook, per README
2. Apply and run the following pipeline, ensuring it outputs the route of the jenkins master, and not `null`
```
kind: "BuildConfig"
apiVersion: "v1"
metadata:
name: my-pipeline
spec:
strategy:
jenkinsPipelineStrategy:
jenkinsfile: |-
echo "Jenkins URL: ${env.JENKINS_URL}"
```
cc: @redhat-cop/containerize-it @pcarney8

Set Jenkins root url in hygieia master

---

zalenium/.applier/group_vars/seed-hosts.yml
zalenium/.applier/hosts
zalenium/.openshift/templates/projects.yml
zalenium/.openshift/templates/zalenium-deployment.yml
zalenium/README.md
zalenium/example-tests/protractor/conf.js
zalenium/example-tests/protractor/simple-test.js
zalenium/requirements.yml

This adds Zalenium deployment. Current Selenium Grid example under [container-pipelines](https://github.com/redhat-cop/container-pipelines/tree/master/cucumber-selenium-grid) uses privileged ClusterRoles that are not always available. Also the upstream [Zelenium](https://opensource.zalando.com/zalenium/) uses Helm Charts that we currently don't have always available.
Once this PR is merged I will update the Selenium Grid example on container-pipelines.
Follow instructions on README.md how to deploy and run simple test from your local machine.

Adding Zalenium (Containerised Selenium Grid)

---

jenkins-masters/hygieia-plugin/.applier/group_vars/seed-hosts.yml
jenkins-masters/hygieia-plugin/.openshift/templates/jenkins-ephemeral.yml
jenkins-masters/hygieia-plugin/.openshift/templates/jenkins-s2i.yml
jenkins-masters/hygieia-plugin/plugins.txt

Apparently the 3.11 jenkins is missing the build-monitor-plugin, which is needed fro the groovy script that sets the root URL. I'm adding it back in.
Spin up the hygieia jenkins quickstart, stand up a pipeline that uses ${JENKINS_URL} and make sure it works.

Adding build-monitor-plugin to custom jenkins master build

---

build-docker-generic/requirements.yml
build-s2i-gows/requirements.yml
build-s2i-jekyll/requirements.yml
build-s2i-liberty/requirements.yml
build-s2i-play/requirements.yml
gitlab-ce/requirements.yml
gogs/requirements.yml
hoverfly/requirements.yml
jenkins-masters/hygieia-plugin/requirements.yml
jenkins-slaves/requirements.yml
mongodb/requirements.yml
rabbitmq/requirements.yml
sonarqube/requirements.yml
tool-box/requirements.yml
zalenium/requirements.yml

This addresses the issue with "oc process" without the "-f" flag when running the task "Create OpenShift objects based on template"
The openshift-applier version 2.06 is causing the following issue for some of the playbooks (MongoDB, RabbitMQ and GitLab at least):
```
TASK [openshift-applier : Create OpenShift objects based on template with params for 'Environment Setup : Create Projects'] ********************************************************************************
failed: [localhost] (item={'oc_path': ''}) => {"changed": true, "cmd": "oc process   https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/v3.9.0/files/projectrequest/template.yml   --param='NAMESPACE=rabbitmq' --param='NAMESPACE_DISPLAY_NAME=rabbitmq'  --ignore-unknown-parameters | oc create  -f - ", "delta": …
```

Upgrade openshfit-applier to v2.0.8

---

tool-box/Dockerfile
tool-box/README.md

Update to latest version of `oc` and latest `ansible 2.6` to address #166 
Follow instructions in the README for building and running the tool-box container.

Update oc and ansible versions, fixes #166

---

sonarqube/.openshift/templates/sonarqube-deployment-template.yml

Adding a post hook to the sonarqube deployment so that in our builds jenkins can be notified on when the quality gate is completed.
Deploy sonarqube and through the admin portal under webhooks you will see the 'jenkins' webhook created.
@sherl0cks

adding post hook to sonarqube deployment template for jenkins

---

jenkins-slaves/jenkins-slave-mvn/Dockerfile
sonarqube/.openshift/templates/sonarqube-deployment-template.yml

Updating the base image to move away from the deprecated image: https://access.redhat.com/containers/#/registry.access.redhat.com/openshift3/jenkins-slave-maven-rhel7/images/v3.6.173.0.146-3.
Additionally, this image will support using a newer version of the oc client @sabre1041 @sherl0cks .

Update Jenkins Maven Slave to Newer Base Image

---

jenkins-slaves/jenkins-slave-npm/Dockerfile
jenkins-slaves/jenkins-slave-npm/Dockerfile.rhel7
jenkins-slaves/jenkins-slave-npm/README.md

Remove the obsolete `COPY contrib/bin/scl_enable /usr/local/bin/scl_enable`
Resolves #191 
1. clone the repo
2. Checkout the branch
3. Change to `jenkins-slaves/jenkins-slave-npm`
4. Run `docker build -t test-npm -f Dockerfile.rhel .`
5. Run resultant container and ensure NPM works: `npm --version`
cc: @redhat-cop/day-in-the-life @oybed @etsauer @haithamshahin333 @sherl0cks

Issue 191   remove scl enable from npm slave

---

jenkins-slaves/.openshift/templates/jenkins-slave-image-mgmt-template.yml
jenkins-slaves/jenkins-slave-image-mgmt/Dockerfile

The PR adds the possibility to add the env RHEL_RELEASEVER to the jenkins-slave-image-mgmt to the template and Dockerfile
In some environment, the hosts which will run the build could be configured in satellite with the set-release option. With this ENV you can override the "7Server" default one
- Setup a host with set-release (for example 7.6)
- Add the env "RHEL_RELEASEVER=7.6" to the buildconfig
it will work
without the env, it will use the default "7Server" and will fail

Added releasever

---

gitlab-ce/.applier/group_vars/seed-hosts.yml
gitlab-ce/.openshift/templates/gitlab-ssl.yml
gitlab-ce/README.md

Extend and modify the existing GitLab CE quickstart with:
- Enable custom certificates to be provided during the deployment phase. These certificates will be stored as Secret keys and will be mounted into the GitLab CE Pod
- Add a new SCC to be used based on `anyuid` SCC so we don't modify the default one
- Use the latest stable GitLab CE container image
- Use the latest stable Redis alpine container image
- Use the latest stable PostgreSQL container image
- Clean up `GITLAB_OMNIBUS_CONFIG` environment variable data to be more clear to read/modify
Follow README instructions to deploy this quickstart
solves #109

Extend GitLab CE deployment to support custom certificates

---

jenkins-slaves/jenkins-slave-golang/Dockerfile
jenkins-slaves/jenkins-slave-golang/Dockerfile.rhel7

The PR adds the possibility to add the env GO_VERSION to the jenkins-slave-golang
- Add the env "GO_VERSION=1.12.1" to the buildconfig
if you don't add the env GO_VERSION it will use the default 1.10.2

added GO_VERSION

---

sonarqube/Dockerfile

This changes the sonarqube Dockerfile to take a list of arguments for plugins.
Run the openshift-applier inventory against a cluster. Ensure that the ARG step is present in the build.

changed sonar Dockerfile to take plugin argument with defaults set

---

jenkins-slaves/jenkins-slave-ruby/Dockerfile
jenkins-slaves/jenkins-slave-ruby/Dockerfile.rhel7

- Replace the CentOS base jenkins image with a RHEL base image
- Update YUM installations to use RHEL repositories
- Use the built-in `oc` client from the Jenkins slave base image
Resolves #195 
From a RHEL host with the appropriate repositories enabled and Docker-latest installed, run:
```
docker build -t jenkins-slave-ruby .
```
cc: @redhat-cop/day-in-the-life @etsauer @lpsantil @sabre1041

Convert Dockerfile to use RHEL Jenkins base image

---

sonarqube/Dockerfile

Resolves #210 
The GitHub/GitLab plugins for SonarQube are deprecated and cause errors since version >= 7.3
- cd sonarqube
- docker build -t sonartest .
- docker run sonartest
- Log in to running sonarqube container
- Navigate to Administration/MarketPlace/Installed
- Verify that the plugins are not  present
cc: @redhat-cop/day-in-the-life @oybed @sabre1041 @etsauer

Remove deprecated github/gitlab plugins for SonarQube

---

jenkins-slaves/jenkins-slave-arachni/README.md

Minor fix into the documentation for arachni jenkins-slaves documentation. 
Tested in OCP4.1.4 environment.
```
[~/containers-quickstarts/jenkins-slaves/jenkins-slave-arachni master ⭑|…1]# oc process -f ../templates/jenkins-slave-generic-template.yml \
>     -p NAME=jenkins-slave-arachni \
>     -p SOURCE_CONTEXT_DIR=jenkins-slaves/jenkins-slave-arachni \
>     | oc create -f -
error: failed to read input object (not a Template?): the path "../templates/jenkins-slave-generic-template.yml" does not exist
error: no objects passed to create
```
```
[~/containers-quickstarts master ⭑|…1]# oc process -f .openshift/templates/jenkins-slave-generic-template.yml   -p NAME=jenkins-slave-arachni -p SOURCE_CONTEXT_DIR=jenkins-slaves/jenkins-slave-arachni | oc create -f - …
```

Minor fix in arachni jenkins-slaves documentation

---

tool-box/Dockerfile

Fixes #230 by updating the oc version to the latest 3.11 release
readme steps should be the same for testing

fixes redhat-cop/containers-quickstarts#230

---

.travis.yml
TESTING.md
_test/setup.sh

We want to make sure we don't get false positives on tests where we're looking in the wrong namespace. To that, the test script now expects to find at least one build.
```
oc login ...
./_test/setup.sh applier esauer-test-scripts etsauer/containers-quickstarts test-script-error && ./_test/setup.sh test esauer-test-scripts etsauer/containers-quickstarts test-script-error
```

Ensure tests fail if there are no builds found

---

.openshift/templates/jenkins-slave-ansible-stacks-template.yml

The default context dir value does not exist. Directory without *-stacks exists.
Process yaml and apply

Updated default context dir value as ansible-stacks no longer exists

---

sonarqube/plugins.sh

Plugin versions were matching on partial version strings... e.g. "7.7" ~ "6.7.7".  This pull request alters the regexp to prevent this partial match.
1. Rebuild the image.
2. Optionally test the new regexp on regexp101.com
3. Validate the list of selected plugins against https://update.sonarsource.org/update-center.properties

BUGFIX: Correct required versions regexp in plugins.sh

---

.applier/group_vars/seed-hosts.yml
jenkins-slaves/jenkins-slave-ansible/Dockerfile
jenkins-slaves/jenkins-slave-ansible/Jenkinsfile.test

Enable python 3.6 env in jenkins-slave-ansible to make ansible work in slave
```
docker build -t jenkins-slave-ansible .
docker run -it --rm jenkins-slave-ansible /bin/bash
$ ansible --version
```

Add scl_enable to jenkins-slave-ansible to enable python 3.6

---

sonarqube/.applier/group_vars/seed-hosts.yml
sonarqube/.openshift/templates/sonarqube-deployment-template.yml
sonarqube/README.md
sonarqube/sonar.properties

The latest upstream release of Sonarqube will not run on Openshift. This PR will let you disable memory mapping for Elasticsearch and let Sonarqube start.
It will also let you specify the upstream version of Sonarqube and thus you can revert to `7.7-community` release if you don't want to disable memory mapping in Elasticsearch.
Follow instructions in README

Fix sonarqube builds and use latest release

---

tool-box/Dockerfile
tool-box/README.md

The current tool-box is using Fedore-30, and Ansible 2.6.
I created a new tool-box using UBI8 base image in addition to the following :
- Updated Ansible version to 2.8
- Add helm client
- Add tekton client
- Add odo CLI tool
- Remove Tree
Docker build using the provided Dockerfile can generate the image with the new tools

Creating UBI8 base tool-box image

---

jenkins-slaves/jenkins-slave-ansible/README.md
jenkins-slaves/jenkins-slave-arachni/README.md
jenkins-slaves/jenkins-slave-golang/README.md
jenkins-slaves/jenkins-slave-gradle/README.md
jenkins-slaves/jenkins-slave-image-mgmt/README.md
jenkins-slaves/jenkins-slave-mongodb/README.md
jenkins-slaves/jenkins-slave-mvn/README.md
jenkins-slaves/jenkins-slave-npm/README.md
jenkins-slaves/jenkins-slave-python/README.md
jenkins-slaves/jenkins-slave-ruby/README.md
jenkins-slaves/jenkins-slave-zap/README.md

- Updated the path to jenkins-slave-generic-template.yml in the Jenkins slave READMEs to point to the correct location. 
- Also, corrected the example in the README for the Ruby slave.
Run the example commands given in each README file.
Resolves #228 

Fix path to jenkins-slave-generic-template in Jenkins slave READMEs

---

.applier/group_vars/seed-hosts.yml
jenkins-slaves/jenkins-slave-mvn/Dockerfile
jenkins-slaves/jenkins-slave-mvn/Jenkinsfile.test

The current `jenkins-slave-mvn` image does not have maven installed. This PR will fix this and also add a test for `mvn`.
Follow instructions in `TESTING.md`

Fix jenkins-slave-mvn to actually have mvn

---

README.md

It will display passing/failing build badge from Prow (instead of Travis)
[![Build Status](https://prow-default.apps.ci-1.cop.rht-labs.com/badge.svg?jobs=cq-daily-master)](https://prow-default.apps.ci-1.cop.rht-labs.com/?job=cq-daily-master)

Use Prow build badge

---

sonarqube/.applier/group_vars/seed-hosts.yml
sonarqube/.openshift/templates/sonarqube-deployment-template.yml
sonarqube/Dockerfile
sonarqube/README.md
sonarqube/sonar.properties

Resolves #257 - Enables authentication by OpenShift by default (turn off in properties file)
Removes windows line breaks from the sonar.properties file (all lines appear modified but only the last 2 are new. All else should be the same)
updates from 7.9 to 7.9.1
1. get MR code on your machine 
2. following instructions in README https://github.com/redhat-cop/containers-quickstarts/tree/master/sonarqube
3. then, since this repo will point the build to the master branch, run a new build  
```
oc start-build sonarqube --from-dir=.. -n sonarqube
```
4. Go to sonar home page. There should now be a 'login with OpenShift link'
5. You should be redirected to the OpenShift login screen. --> Login.
6. You should be redirected to Sonarqube and see the projects page (empty)
cc: …

sonarqube: use openshift oauth for login

---

.applier/group_vars/seed-hosts.yml
.openshift/templates/jenkins-slave-generic-template.j2
jenkins-slaves/jenkins-slave-ansible/Dockerfile
jenkins-slaves/jenkins-slave-arachni/Dockerfile
jenkins-slaves/jenkins-slave-golang/Dockerfile
jenkins-slaves/jenkins-slave-gradle/Dockerfile
jenkins-slaves/jenkins-slave-mongodb/Dockerfile
jenkins-slaves/jenkins-slave-mvn/Dockerfile
jenkins-slaves/jenkins-slave-python/Dockerfile
jenkins-slaves/jenkins-slave-ruby/Dockerfile

Updated the jenkins slaves to use 4.2 as their base.
- Check prow logs, builds should pass.
- Build slaves manually via applier instructions in each directory

Updated jenkins slaves to 4.2 bases

---

_test/rabbitmq.sh

Remove unnecessary check for builds in RabbitMQ test 
```
./_test/rabbitmq.sh applier rabbitmq-test pabrahamsson/containers-quickstarts remove_rabbit_build_check && ./_test/rabbitmq.sh test rabbitmq-test pabrahamsson/containers-quickstarts remove_rabbit_build_check
```

Remove rabbit build check

---

rabbitmq/Dockerfile

This PR fixes running RabbitMQ's docker build under a firewall
Just run a `docker build . -t rabbitmq` under `rabbitmq` folder.
cc: admachad at redhat.com

Fixes running the RabbitMQ build under a firewall

---

helm-charts/eap72/Chart.yaml
helm-charts/eap72/README.md
helm-charts/eap72/templates/NOTES.txt
helm-charts/eap72/templates/buildconfig.yaml
helm-charts/eap72/templates/deploymentconfig.yaml
helm-charts/eap72/templates/imagestream.yaml
helm-charts/eap72/templates/ping-service.yaml
helm-charts/eap72/templates/route.yaml
helm-charts/eap72/templates/secret.yaml
helm-charts/eap72/templates/server-service.yaml
helm-charts/eap72/templates/tests/pod.yaml
helm-charts/eap72/values.yaml

This is a simple Helm chart for deploying a Java application on EAP 7.2. This chart will deploy a BuildConfig and ImageStream for performing an s2i build. Once the image is built, it will automatically be rolled out via a DeploymentConfig image trigger. 
Users can enable TLS by providing two different OpenShift secrets, described in this chart's readme and NOTES.txt.
Future features can be added to enable SSO, add datasources, leverage service serving certificates, etc, unless requested by maintainers for this PR.
This chart provides a test hook that will run "curl" against the application's service. Test the chart by running `helm test $RELEASE_NAME` after the EAP pod is in a ready state. The resulting output will display whether the test passed or not.

created a basic eap 7.2 Helm chart

---

_test/setup.sh

We only need to display jenkins pipeline output if the build type is `JenkinsPipeline`

Only show Jenkins logs for JenkinsPipeline builds

---

tool-box/Dockerfile

Cleans up the helm installation as part of the toolbox. `helm init` isn't a command or required anymore. So we can remove it from the dockerfile.
CI

Toolbox - Remove unnecessary helm init command

---

helm-charts/eap72/README.md
helm-charts/eap72/templates/NOTES.txt
helm-charts/eap72/templates/buildconfig.yaml
helm-charts/eap72/templates/deploymentconfig.yaml
helm-charts/eap72/templates/route.yaml
helm-charts/eap72/templates/secret.yaml
helm-charts/eap72/templates/server-service.yaml
helm-charts/eap72/templates/tests/pod.yaml
helm-charts/eap72/values.yaml

Improving EAP72 Helm chart by adding ux enhancements and bug fixes.
Changes include:
- Changing jgroups keystore from pkcs12 to jceks (was causing "Invalid keystore format" errors)
- Disabling bc triggers (was causing a confusing user experience because the initial installation was auto-triggering, but upgrades were not)
- Grouping all tls-related values under a `tls` map
- Adding tls.httpsSecret value (default to https-keystore)
- Saving https keystore secret in OCP secret
- Changing default keystore password to "changeit"
- Various README edits
"helm test" command after installing the chart to an ocp cluster

Various UX improvements and bug fixes to eap72 chart.

---

ubi8-asciidoctor/.openshift/bc-ubi8-asciidoctor.yml
ubi8-asciidoctor/Dockerfile
ubi8-asciidoctor/README.md

Contains the toolset of asciidoctor which was based on Alpine but in this container it is ubi-minimal based. We have a ubi8 based toolset to for instance generate pdf's from an asciidocotor document.
You could build the docker image and run it if you like. We are using these images in an internal pipeline at the moment but thought it best to share them with the world.
```
podman run --rm --name asciidoctor  -v ./:/documents/  -w /documents/ ubi8-asciidoctor      asciidoctor-pdf -r asciidoctor-diagram -a ej-base-dir=/documents/ -a ej-projectdir=/documents/ document.adoc
```

Ubi8 asciidoctor

---

ubi8-git/.openshift/bc-ubi8-git.yml
ubi8-git/Dockerfile
ubi8-git/README.md
ubi8-google-api-python-client/.openshift/bc-ubi8-google-api-python-client.yml
ubi8-google-api-python-client/Dockerfile
ubi8-google-api-python-client/README.md

Adds two utility images useful for use in GitLab CI pipelines, but could be used in other places to.
You could build the docker image and run it if you like. We are using these images in an internal pipeline at the moment but thought it best to share them with the world.

ubi8-git and ubi8-google-api-python-client - init add

---

ubi8-git/Dockerfile
ubi8-google-api-python-client/Dockerfile

Fixes the source for the ubi8 image to be explicate so it can build in quay.io
example: https://quay.io/repository/itewk/ubi8-git?tab=builds

ubi8-git and ubi8-google-api - update to use registry.access.redhat.com/ubi8

---

README.md
motepair/.helmignore
motepair/Chart.yaml
motepair/README.md
motepair/templates/NOTES.txt
motepair/templates/_helpers.tpl
motepair/templates/buildconfig.yaml
motepair/templates/deploymentconfig.yaml
motepair/templates/imagestream.yaml
motepair/templates/route.yaml
motepair/templates/service.yaml
motepair/values.yaml

Add Helm 3 chart for build/deploy of [motepair](https://github.com/motepair/motepair-server)
Resolves #315
```
git clone git@github.com:redhat-cop/containers-quickstarts.git
cd containers-quicktstarts/motepair
git checkout Issue-315-_-Add_motepair_build_deploy_ability
helm install motepair ./
```

Added Helm 3 chart for motepair

---

.applier/group_vars/seed-hosts.yml
jenkins-slaves/jenkins-slave-gradle/Dockerfile
jenkins-slaves/jenkins-slave-gradle/Jenkinsfile.test
jenkins-slaves/jenkins-slave-gradle/ubi.repo
jenkins-slaves/jenkins-slave-mongodb/Dockerfile
jenkins-slaves/jenkins-slave-mongodb/Jenkinsfile.test
jenkins-slaves/jenkins-slave-npm/Jenkinsfile.test
jenkins-slaves/jenkins-slave-python/Dockerfile
jenkins-slaves/jenkins-slave-python/Jenkinsfile.test

Add CI for gradle, mongodb, npm & python jenkins agents
Use `./_test/setup.sh applier && ./_test/setup.sh test`

Add CI tests for gradle, mongodb, npm & python jenkins agents

---

nexus/README.md
nexus/chart/nexus/.gitignore
nexus/chart/nexus/.helmignore
nexus/chart/nexus/Chart.yaml
nexus/chart/nexus/README.md
nexus/chart/nexus/templates/rolebinding.yaml
nexus/chart/nexus/values.yaml

This adds an initial helm chart to deploy Sonatype Nexus. This instance will include the Nexus Kubernetes plugin and will deploy the Red Hat and JBoss Maven repositories by default. This builds off of an upstream chart by pulling it in as a dependency while we work with the upstream chart owners to merge in our changes. Eventually we'll be able to remove our custom work here and just have instructions that say "use this upstream chart with the provided values file in this repo".
From the `nexus/chart/nexus` directory, run:
```
oc new-project nexus-test
helm dep up
helm install nexus .         (<-- notice the trailing dot)
``` 
Once that's been deployed, you should see a running Nexus instance and can login with the default admin credentials of `admin:admin123)`
cc: …

Add initial Nexus helm chart

---

README.md
ubi7-gitlab-runner/README.md
utilities/README.md
utilities/ubi8-asciidoctor/README.md
utilities/ubi8-git/README.md
utilities/ubi8-google-api-python-client/README.md

This will update a few broken links in Markdown documents.
**NOTE:** There are still two broken links in [s2i-liberty/README](/redhat-cop/containers-quickstarts/blob/master/build-s2i-liberty/README.md#considerations-on-http-session-failover) that I haven't found updated pages for.
I also plan to add a CI test for this that will address #304 
```
podman run -it --rm -v $PWD:/code:z registry.access.redhat.com/ubi8/nodejs-12 bash -c 'npm install --save-dev markdown-link-check && find /code -type f -name "*.md" -exec markdown-link-check --quiet --config /code/linkcheck-config.json {} \;'
```

Fix broken links in Markdown documents

---

build-s2i-liberty/README.md

Fix two broken links in [build-s2i-liberty/README.md](/redhat-cop/containers-quickstarts/blob/master/build-s2i-liberty/README.md#considerations-on-http-session-failover).
```
podman run -it --rm -v $PWD:/code:z registry.access.redhat.com/ubi8/nodejs-12 bash -c 'npm install --save-dev markdown-link-check && find /code -type f -name "*.md" -exec markdown-link-check --quiet --config /code/linkcheck-config.json {} \;'
```

Fix broken s2i-liberty links

---

gogs/.openshift/templates/gogs-persistent-template.yaml
hoverfly/.openshift/templates/hoverfly-deployment-template.yml

The keys removed are duplicates and are already specified in the template with another value

Removed duplicate keys

---

gitlab-ce/.openshift/templates/gitlab-ssl.yml
gogs/.openshift/templates/gogs-persistent-template.yaml
mongodb/.openshift/templates/configsvr.yml
mongodb/.openshift/templates/replset.yml
rabbitmq/.openshift/templates/deployments/template.yml

As per other PRs related to apiVersions. Moves SCCs to be v4

Updated apiVersions to fully qualified 4.x compatible for SecurityContextConstraints

---

_test/conftest.sh

Enabled helm tests as below is merged:
- https://github.com/redhat-cop/github-actions/pull/8
Check helm tests execute.

Removed skip for helm related conftests

---

.applier/group_vars/seed-hosts.yml
.openshift/templates/jenkins-slave-image-mgmt-template.yml
_test/setup.sh
jenkins-slaves/jenkins-slave-image-mgmt/Dockerfile
jenkins-slaves/jenkins-slave-image-mgmt/Jenkinsfile.test
jenkins-slaves/jenkins-slave-image-mgmt/README.md

Update `jenkins-slave-image-mgmt` to use UBI base image and latest version of Skopeo.
Wait for prow to do it for you or use instructions below.
```
oc new-project test-skopeo
./_test/setup.sh applier test-skopeo pabrahamsson/containers-quickstarts jenkins-agent-image-mgmt
./_test/setup.sh test test-skopeo pabrahamsson/containers-quickstarts jenkins-agent-image-mgmt
```

Update Jenkins Image Mgmt to use UBI & latest skopeo

---

_test/_helpers.bash
_test/conftest.sh

The output of the conf tests gives no indication as to what is failing thus increasing the feedback loop for debugging. I've written a simple bit of bash to capture the needed output. As per the example below:
Make one of the templates not valid, eg change a `apiVersion: template.openshift.io/v1` to just `v1`. Run the conf tests. See the error. 🧙‍♂️

🏏 Output of failed tests swallowed. Fixing 🦇

---

tool-box/Dockerfile
tool-box/README.md

The Docs for Toolbox are out of date. 
The build for ODO contains an invalid URL but was not failing the `docker build`
Bump some versions
`docker build -t `....

🦄 Tidy up docs for Toolbox and fix broken build 🔥

---

build-s2i-python-kopf/s2i/run

The `KOPF_NAMESPACED` flag currently does not behave as expected when combined with `KOPF_PEERING` resulting in namespaced deployments attempting to create `ClusterKopfPeering` resources rather than the namespaced `KopfPeering`.
This fixes the issue by setting `KOPF_NAMESPACE` when `KOPF_NAMESPACED` is specified.
Test instructions in provided examples and documentation.

Set KOPF_NAMESPACE when KOPF_NAMESPACED is set

---

jenkins-slaves/jenkins-slave-ruby/Dockerfile

Updating the ruby jenkins agent oc client to 4.4.
Alternatively, we could remove the custom installation of the `oc` client altogether and depend entirely on the base image to provide it. However, it does provide a slightly older version of the client as demonstrated below.
```console
$ podman run --rm --entrypoint "/bin/bash" quay.io/openshift/origin-jenkins-agent-base:4.4 -c 'oc version'     
Client Version: v4.2.0-alpha.0-459-gd038424
```
Does anyone have any thoughts regarding this?
Standard ruby agent tests.

Update ruby jenkins agent oc client to 4.4

---

jenkins-slaves/jenkins-slave-helm/Dockerfile
jenkins-slaves/jenkins-slave-helm/Jenkinsfile.test
jenkins-slaves/jenkins-slave-helm/README.md
jenkins-slaves/jenkins-slave-helm/scl_enable
jenkins-slaves/jenkins-slave-helm/ubi.repo

Adds [ct](https://github.com/helm/chart-testing) to jenkins-slave-helm. Closes #387 
Run the Jenkinsfile.test pipeline to make sure ct and each of ct's dependencies are installed.
I also have a pipeline at https://github.com/deweya/-Learn-Helm/blob/feat/ct-test/helm-charts/Jenkinsfile that can be used to test ct functionality. I have the namespace hardcoded in it, so it'd probably be best to make a fork so that you can change the namespace. If you want to use this pipeline to test, be sure to import it as a multibranch pipeline job and set the Jenkinsfile path to `helm-charts/Jenkinsfile`.

adding "ct" tool to jenkins-slave-helm

---

jenkins-agents/jenkins-agent-ansible/Dockerfile
jenkins-agents/jenkins-agent-ansible/Jenkinsfile.test

Add molecule to pip install in jenkins-slave-ansible. As well, needed to set LC_ALL and LANG as ENV for molecule to work
Locally,
Build locally, and then run molecule --version in running container
On OCP,
Process and template (command provided in README).
Run sample pipeline using jenkins-slave-ansible label and use molecule command.
This should create an image stream with a jenkins-slave label, so that Jenkins picks it up as an available slave. 
```
pipeline {
agent {
label 'jenkins-slave-ansible'
}
stages {
stage ('Get latest code') {
steps {
checkout scm
}
}
stage ('Molecule check') {
steps {
sh '''
ansible --version
molecule --version
'''
}
}
}
}
```

add molecule to jenkins-slave-ansible Dockerfile

---

cert-manager-configs/.applier/group_vars/seed-hosts.yml
cert-manager-configs/.applier/host_vars/localhost.yml
cert-manager-configs/.applier/hosts
cert-manager-configs/.openshift/cert-manager.yml
cert-manager-configs/.openshift/cert-utils-operator.yml
cert-manager-configs/.openshift/ocpv4-certs.yml
cert-manager-configs/README.md

Adding support for cert-manager / OCPv4 for use with openshift-applier
Tweak the params, then run the openshift-applier with the inventory

Cert Management: Adding OCP v4 templates for use with OpenShift Applier

---

tool-box/Dockerfile
tool-box/README.md

The README for the `tool-box` had the wrong command to run with `docker., which is now fixed + bumping versions of various components to the latest stable versions. 
Run the `tool-box` container 

tool-box: Fixing README bug + updating versions

---

utilities/ubi8-asciidoctor/Dockerfile
utilities/ubi8-asciidoctor/version.json

- Updates the images to the latest released asciidoctor products
- removed kindlegen product because upstream (asciidoctor did this also) 
- update version.json from 1.1 into 1.2
Create the image and check the output of the pdf ....
docker run --rm --name asciidoctor -v /<report-dir>/:/documents/ -w /documents/styles quay.io/redhat-cop/ubi8-asciidoctor:1.2 asciidoctor-pdf -r asciidoctor-diagram -a ej-base-dir=/documents/  <document.adoc>

Update asciidoctor image to latest released versions

---

utilities/ubi8-asciidoctor/Dockerfile
utilities/ubi8-asciidoctor/version.json

* Use ubi8 instead of ubi8-minimal.
When installing so much (esp. python) there's barely any difference.
Yet, one can leverage full dnf in ubi8
* Less layers with curl | tar
* Install gcc, make etc. -> install gems -> remove gcc, make etc. all in one layer
This saves up to 300M
* Cleanup cache and docs where reasonable
Create the image and check the output of the pdf ....
```bash
podman run --rm --name asciidoctor -v //:/documents/ -w /documents/styles quay.io/redhat-cop/ubi8-asciidoctor:1.3 asciidoctor-pdf -r asciidoctor-diagram -a ej-base-dir=/documents/<document.adoc>
```

Make utilities/ubi8-asciidoctor image significantly smaller

---

jenkins-agents/jenkins-agent-ansible/Dockerfile

The 2.8.2 version does not support the anisble k8s module.
Update ansible version 
Build container. 

Update ansible version

---

jenkins-agents/jenkins-agent-ansible/Dockerfile

Improvements:
- Update jenkins base image from 4.4 > 4.5 (prep for move from ubi7 to ubi8)
- Reformat Dockerfile for ease of troubleshooting / testing
- Remove user-interactive build breaking cmd
- Flip ansible version from env to arg
- Variablize yum install flags
- Variablize Pip & yum package instal lists
- Enable BASH_XTRACEFD for improved build pipeline debugging
Build as usual to test.

refactor dockerfile & update Jenkins base to 4.5

---

cert-manager-configs/.openshift/cert-manager.yml
cert-manager-configs/.openshift/cert-utils-operator.yml
cert-manager-configs/.openshift/ocpv4-certs.yml
cert-manager-configs/.openshift/route-with-cert.yml

Follow-up PR to #403 to allow for OCP template use to create a vanity route with valid certificate
Run the oc process command, e.g.:
```
oc process --local -f route-with-cert.yml -p NAME=test -p NAMESPACE=test -p FQDN=test.example.com -o yaml
```

Adding vanity route + cert OCP template

---

hygieia/.openshift/templates/build-base-image.yml
hygieia/.openshift/templates/build-exec-ui.yml
hygieia/.openshift/templates/build-hygieia-jenkins-collector.yml
hygieia/.openshift/templates/build-java-component.yml
hygieia/.openshift/templates/build-ui.yml

Fixing image versions (nodejs:8 not in 4.5 openshift and java:latest will not build - so fixed to java:8)
Ensure playbook runs and app stands up.  Tested locally with:
```
export ANSIBLE_INVALID_TASK_ATTRIBUTE_FAILED=False
ansible-playbook -i .applier/ galaxy/openshift-applier/playbooks/openshift-cluster-seed.yml -e filter_tags=all -e skip_version_checks=true
```

fix images to java:8 and nodejs:10 for hygieia

---

utilities/ubi8-asciidoctor/Dockerfile
utilities/ubi8-asciidoctor/version.json

Without it, the user has / as home implicitly,
which breaks some commands that create files in users home

asiidoctor-pdf: Add HOME env

---

cert-manager-configs/.openshift/cert-utils-operator.yml

Latest cert-utils-operator supports `AllNamespaces` rather than `SingleNamespace` install mode. Adding an empty list will allow the operator installation to properly complete.
This can be installed independently with the following
```bash
oc process --local -f cert-manager-configs/.openshift/cert-utils-operator.yml | oc apply -f -
```

Update cert-utils-operator target namespaces

---

jenkins-agents/jenkins-agent-argocd/Dockerfile

The `YQ_VERSION` should be vX.Y.Z. 
I've also bumped the `YQ_VERSION` to 4.5.1 whilst I'm at it.
Closes #438 
Build argocd agent and run `yq` command and see it works

Fix to helm-agent-argocd

---

jenkins-agents/jenkins-agent-helm/Dockerfile

yq v3 will not be supported beyond August so probably best to move onto this, especially as the `jenkins-agent-argocd` is already using yq v4. There are compatibility issues between 3 and 4 (something I have found on the argocd agent, [see the yq docs](https://mikefarah.gitbook.io/yq/v/v4.x/upgrading-from-v3) for more details).
I haven't made a change on all the other YQ_VERSIONS in this repo as they are for the testing frameworks etc. which I think could break other things elsewhere.
N/A

Bump YQ_VERSION to 4.5.1

---

jenkins-agents/jenkins-agent-conftest/Dockerfile

This image is currently failing to build which this PR fixes. It also include some cleanup and version updates.
```
STEP 1: FROM quay.io/redhat-cop/jenkins-agent-python:v1.0
Getting image source signatures
Copying blob 791696e2ff97 done
Copying blob 911e72d1d7d7 done
Copying blob fecf0868d374 done
Copying blob 0c983affa284 done
Copying blob f7db571f3a05 done
Copying blob 050d08c748fb done
Copying blob b9ef6a88723f done
Copying blob f4f449dd7a0e done
Copying blob 48d8cd37b9f4 done
Copying config e68a2afeef done
Writing manifest to image destination
Storing signatures
STEP 2: ENV BATS_VERSION=1.2.0     YQ_VERSION=3.3.2     CONFTEST_VERSION=0.18.2
STEP 3: USER root
STEP 4: RUN curl --fail -skL https://github.com/open-policy-agent/conftest/releases/download/v${CONFTEST_VERSION}/conftest_${ …
```

FIX: fix for jenkins-agent-conftest build failure

---

jenkins-agents/jenkins-agent-argocd/Dockerfile
jenkins-agents/jenkins-agent-graalvm/Dockerfile
jenkins-agents/jenkins-agent-graalvm/Jenkinsfile.test
jenkins-agents/jenkins-agent-graalvm/README.md
jenkins-agents/jenkins-agent-zap/Dockerfile

updates the graalvm jenkins agent to use the madrel drop in replacement
add in common tools (updated oc, helm, yq, yq)
supercedes/replaces - https://github.com/redhat-cop/containers-quickstarts/pull/429
See Jenkinsfile test

🐟 mandrel drop in 🐟

---

.github/workflows/ubi8-bats-pr.yaml
.github/workflows/ubi8-bats-publish.yaml
utilities/ubi8-bats/Dockerfile
utilities/ubi8-bats/buildah.sh
utilities/ubi8-bats/test/unit.bats
utilities/ubi8-bats/version.json

Update versions of utilities and switch GH actions to use buildah and podman
>BATS_VERSION=1.2.1
HELM_VERSION=3.5.2
JQ_VERSION=1.6
OC_VERSION=4.7
YQ_VERSION=3.4.1
GH Actions will do it

Update ubi-bats utility version + buildah & podman actions

---

utilities/ubi8-asciidoctor/Dockerfile
utilities/ubi8-asciidoctor/version.json

some commands, like `git config --global` are failing due to missing or inappropriate HOME

asciidoctor-pdf image: Move home out of a mounted volume

---

rabbitmq/.openshift/templates/builds/template.yml
rabbitmq/.openshift/templates/imagestreams/images.yml
rabbitmq/Dockerfile

Use ubi-minimal:8.3 as base image for RabbitMQ
```
./_test/rabbitmq applier rabbitmq-test pabrahamsson/containers-quickstarts rabbitmq_ubi_minimal-8
./_test/rabbitmq test rabbitmq-test pabrahamsson/containers-quickstarts rabbitmq_ubi_minimal-8
```

Change RabbitMQ to use ubi-minimal:8

---

build-s2i-python-kopf/examples/kopf-simple/README.adoc
build-s2i-python-kopf/examples/kopf-simple/operator/operator.py
build-s2i-python-kopf/s2i/run

- Fix kopfclusterpeering existence check
- The oc commands to create kopfpeering resources should specify the kopf.dev domain
- Improvements to the python kopf simple example.
Documented in the README

build-s2i-python-kopf fix peering and example improvements

---

rabbitmq/chart/templates/deployment.yaml
rabbitmq/test/acceptance/_helpers.bash
rabbitmq/test/acceptance/rabbitmq.bats

This is the first step in migrating from [openshift-applier](https://github.com/redhat-cop/openshift-applier) to Helm and Bats.
Bats will run unit tests against the included RabbitMQ Helm chart and then use the same chart do deploy a RabbitMQ cluster and run acceptance tests. 
You'll need `oc`, `helm`, `yq` & `bats` and an OpenShift cluster where you can create namespaces/projects.
```
bats rabbitmq/test/unit rabbitmq/test/acceptance
```

RabbitMQ migration to Bats & Helm for testing

---

rabbitmq/chart/templates/_helpers.tpl
rabbitmq/chart/templates/deployment.yaml
rabbitmq/chart/values.yaml
rabbitmq/test/unit/statefulset.bats

The RabbitMQ Anti affinity settings were not using the correct label to match RabbitMQ pods.
Also refactor the HA (affinity) settings.
This will be tested by the CI job
```
helm install rabbitmq rabbitmq/chart
bats rabbitmq/test/acceptance
```

RabbitMQ HA (anti affinity) fix

---

sonarqube/.applier/group_vars/seed-hosts.yml
sonarqube/Dockerfile
sonarqube/plugins.sh

Update Sonarqube to `7.9.6` and add support for updating existing plugins.
This is needed because the `pmd` plugin requires a newer version of the `java` plugin.
```bash
ansible-galaxy install -r requirements.txt -p galaxy
ansible-playbook -i .applier galaxy/openshift-applier/playbooks/openshift-cluster-seed.yml -e build_repo='https://github.com/pabrahamsson/containers-quickstarts.git' -e build_ref=sq_java_plugin
```
There should not be any errors in sonarqube about `pmd` needing a newer version of the `java` plugin.

Sonarqube: update to 7.9.6 + support updating plugins

---

_test/rabbitmq.sh
rabbitmq/.openshift/templates/configmaps/config.yml
rabbitmq/.openshift/templates/deployments/template.yml
rabbitmq/chart/templates/configmap.yaml
rabbitmq/chart/templates/deployment.yaml
rabbitmq/chart/values.yaml
rabbitmq/test/acceptance/rabbitmq.bats
rabbitmq/test/unit/service.bats

Enable RabbitMQ Prometheus metrics endpoint, needs #446 to be merged first
This repo CI should test this but can also be tested manually
```
bats rabbitmq/test/unit rabbitmq/test/acceptance
```

Enable prometheus scraping endpoint

---

.github/workflows/build-s2i-python-kopf-pr.yaml
.github/workflows/build-s2i-python-kopf-publish.yaml
.github/workflows/conftest.yaml
.github/workflows/github-runner-ubi8.yaml
.github/workflows/jenkins-agent-image-mgmt-pr.yaml
.github/workflows/jenkins-agent-image-mgmt-publish.yaml
.github/workflows/jenkins-agent-python-pr.yaml
.github/workflows/jenkins-agent-python-publish.yaml
.github/workflows/rabbitmq-pr.yaml
.github/workflows/rabbitmq-publish.yaml
.github/workflows/tekton-task-images-conftest-pr.yaml
.github/workflows/tekton-task-images-conftest-publish.yaml
.github/workflows/tekton-task-images-helm-pr.yaml
.github/workflows/tekton-task-images-helm-publish.yaml
.github/workflows/ubi7-gitlab-runner-pr.yaml
.github/workflows/ubi7-gitlab-runner-publish.yaml
.github/workflows/ubi8-asciidoctor-pr.yaml
.github/workflows/ubi8-asciidoctor-publish.yaml
.github/workflows/ubi8-git-pr.yaml
.github/workflows/ubi8-git-publish.yaml
.github/workflows/ubi8-google-api-python-client-pr.yaml
.github/workflows/ubi8-google-api-python-client-publish.yaml

`docker/build-and-push@v1` has been deprecated so this seemed like a good time to switch to using `redhat-actions/buildah-build@v2` and `redhat-actions/push-to-registry@v2`.
These actions are already being used by `ubi8-bats`.
Should be handled by the CI for this repo

Update GH actions to use redhat-actions for build & publish

---

jenkins-agents/jenkins-agent-conftest/README.md
jenkins-agents/jenkins-agent-helm/Dockerfile
jenkins-agents/jenkins-agent-helm/Jenkinsfile.test

Bounced some versions and added conftest binary to this image. Reason I've added it is as in my pipeline i want to `helm template my chart --output-dir policy/helm-output` and run some policy checks on the generated template artifacts. Having the conftest binary and helm ones in separate agents is time wasted waiting for Jenkins to fire up another agent. 
let ci do it's thing? you could also docker build or follow the readme's instructions 🤷‍♀️

🐧 ADD conftest to helm agent and UPDATE versions 🐧

---

.github/workflows/build-s2i-python-kopf-publish.yaml
.github/workflows/jenkins-agent-image-mgmt-publish.yaml
.github/workflows/jenkins-agent-python-publish.yaml
.github/workflows/rabbitmq-publish.yaml
.github/workflows/tekton-task-images-conftest-publish.yaml
.github/workflows/tekton-task-images-helm-publish.yaml
.github/workflows/ubi7-gitlab-runner-publish.yaml
.github/workflows/ubi8-asciidoctor-publish.yaml
.github/workflows/ubi8-git-publish.yaml
.github/workflows/ubi8-google-api-python-client-publish.yaml

With the switch to `redhat-actions/buildah-build`, it expects the tags to be [separated by space](https://github.com/redhat-actions/buildah-build#action-inputs) rather than a comma.
CI will publish images once merged.
Resolves #474 

GH buildah-build action needs space separated tags

---

tekton-task-images/conftest/Dockerfile
tekton-task-images/helm/Dockerfile

Will update the openssl version in the [tekton task images](https://quay.io/repository/redhat-cop/tekton-task-conftest/manifest/sha256:21ca8e0b2001610afcae8be481a7a9582fc4366a7cb892f203a83e0ca4f50896?tab=vulnerabilities) to resolve [RHSA-2021:1024](https://access.redhat.com/errata/RHSA-2021:1024)
It will also add a default uid to the conftest image.
```bash
$ podman build -t tekton-task-conftest tekton-task-images/conftest
$ podman run -it --rm tekton-task-conftest bash -c 'rpm -q openssl'
openssl-1.1.1g-15.el8_3.x86_64
```

Update Tekton Task image packages to resolve openssl RHSA-2021:1024

---

_test/conftest.sh
tower-ocp-custom/.applier/group_vars/seed-hosts.yml
tower-ocp-custom/.applier/hosts
tower-ocp-custom/.openshift/templates/tower-ocp-custom-image.yml
tower-ocp-custom/README.md
tower-ocp-custom/requirements.yml

This quickstart gives an example of how to deploy a custom Ansible Tower image with custom virtualenvs and RPMs directly to your Openshift internal image registry to be consumed by the Ansible Tower 3.8 installer.
Following the steps in the README will yield a buildconfig and an imagestream in your Openshift cluster. Run the applier, and validate:
```bash
$ oc get buildconfig tower-ocp -n tower-ocp
$ oc get imagestream tower-ocp -n tower-ocp
```

Add tower custom buildconfig

---

tekton-task-images/helm/Dockerfile

Building this image currently fails because `openssl` isn't installed.
This should also make #496 pass CI tests
```
STEP 5: RUN source /tmp/version &&   curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 &&   chmod 700 get_helm.sh &&   ./get_helm.sh --version ${HELM_VERSION}
In order to verify checksum, openssl must first be installed.
Please install openssl or set VERIFY_CHECKSUM=false in your environment.
Failed to install helm with the arguments provided: --version v3.5.3
Accepted cli arguments are:
[--help|-h ] ->> prints this help
[--version|-v <desired_version>] . When not defined it fetches the latest release from GitHub
e.g. --version v3.0.0 or -v canary
[--no-sudo]  ->> install without sudo
For support, go to …
```

BUGFIX: Use openssl to verify Helm checksum

---

.github/workflows/github-runner-ubi8.yaml

Switch to https://github.com/redhat-actions/push-to-registry for pushing image to quay.io.
Also switching to `ubuntu-20.04` [per recommendation](https://github.com/redhat-actions/push-to-registry#note-about-github-runners-and-podman).
This should also make #509 obsolete
Should be done by CI :green_heart: 

Use redhat-actions/push-to-registry for github-runner image

---

jenkins-agents/jenkins-agent-ansible/Dockerfile
jenkins-agents/jenkins-agent-arachni/Dockerfile
jenkins-agents/jenkins-agent-argocd/Dockerfile
jenkins-agents/jenkins-agent-conftest/Dockerfile
jenkins-agents/jenkins-agent-cosign/Dockerfile
jenkins-agents/jenkins-agent-erlang/Dockerfile
jenkins-agents/jenkins-agent-golang/Dockerfile
jenkins-agents/jenkins-agent-graalvm/Dockerfile
jenkins-agents/jenkins-agent-gradle/Dockerfile
jenkins-agents/jenkins-agent-helm/Dockerfile
jenkins-agents/jenkins-agent-helm/Jenkinsfile.test
jenkins-agents/jenkins-agent-hugo/Dockerfile
jenkins-agents/jenkins-agent-image-mgmt/Dockerfile
jenkins-agents/jenkins-agent-mongodb/Dockerfile
jenkins-agents/jenkins-agent-mvn/Dockerfile
jenkins-agents/jenkins-agent-npm/Dockerfile
jenkins-agents/jenkins-agent-python/Dockerfile
jenkins-agents/jenkins-agent-ruby/Dockerfile
jenkins-agents/jenkins-agent-rust/Dockerfile

- update Jenkins Agents to use a 4.8 base image
- remove usage of `-k` with `curl` in Jenkins Agent Dockerfiles
- use `curl <url> | tar zxf - -C <path>` pattern to reduce `Dockerfile` size
- Default to use latest stable version of `oc` client (when installed)
Should be covered by CI
Can also be tested manually
```bash
./_test/setup.sh applier container-quickstarts-tests pabrahamsson/containers-quickstarts feature/jenkins-agent-4.8-base
./_test/setup.sh test container-quickstarts-tests pabrahamsson/container-quickstarts feature/jenkins-agent-4.8-base
```

Update Jenkins Agent base images to 4.8 + minor improvements

---

utilities/ubi8-asciidoctor/Dockerfile
utilities/ubi8-asciidoctor/version.json

Image [builds](https://github.com/redhat-cop/containers-quickstarts/runs/3625749951?check_suite_focus=true) are failing due to missing `python.h` header file.
```bash
podman build -t ubi8-asciidoctor .
```

FIX: Add python3-devel to fix ubi8-asciidoctor build

---

jenkins-agents/jenkins-agent-ansible/Dockerfile
jenkins-agents/jenkins-agent-ansible/Jenkinsfile.test
jenkins-agents/jenkins-agent-graalvm/Jenkinsfile.test
jenkins-agents/jenkins-agent-helm/Dockerfile
jenkins-agents/jenkins-agent-helm/Jenkinsfile.test
jenkins-agents/jenkins-agent-python/Dockerfile
jenkins-agents/jenkins-agent-python/Jenkinsfile.test
jenkins-agents/jenkins-agent-python/version.json

The jenkins-agent-ansible image installs `python38` which through dependencies also updates `chkconfig`. `chkconfig` will update the permissions on `/var/lib/alternatives` and `/etc/alternatives` (`755`), this breaks the `alternatives` command (called as part of the `ENTRYPOINT`).
```
bash-4.4$ /usr/local/bin/run-jnlp-client
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
failed to create /var/lib/alternatives/java.new: Permission denied
```
This PR will "reset" the permissions on `/var/lib/alternatives` and `/etc/alternatives` to the [upstream settings](https://github.com/openshift/jenkins/blob/release-4.8/slave-base/Dockerfile.localdev#L34-L35).
It will also add a test to ensure the `java` executable is in good order.
CI should ensure we now have a working jvm. …

Fix broken permissions in Jenkins agents using Python 

---

.applier/group_vars/seed-hosts.yml
jenkins-agents/jenkins-agent-ansible/Dockerfile
jenkins-agents/jenkins-agent-arachni/Dockerfile
jenkins-agents/jenkins-agent-argocd/Dockerfile
jenkins-agents/jenkins-agent-cosign/Dockerfile
jenkins-agents/jenkins-agent-erlang/Dockerfile
jenkins-agents/jenkins-agent-golang/Dockerfile
jenkins-agents/jenkins-agent-graalvm/Dockerfile
jenkins-agents/jenkins-agent-gradle/Dockerfile
jenkins-agents/jenkins-agent-helm/Dockerfile
jenkins-agents/jenkins-agent-hugo/Dockerfile
jenkins-agents/jenkins-agent-image-mgmt/Dockerfile
jenkins-agents/jenkins-agent-mongodb/Dockerfile
jenkins-agents/jenkins-agent-mvn/Dockerfile
jenkins-agents/jenkins-agent-npm/Dockerfile
jenkins-agents/jenkins-agent-python/Dockerfile
jenkins-agents/jenkins-agent-ruby/Dockerfile
jenkins-agents/jenkins-agent-rust/Dockerfile

Update Jenkins Agent base images to 4.9 where applicable
Will be done by CI or
```
git clone https://github.com/pabrahamsson/containers-quickstarts -b feature/jenkins-agent-4.9-base
cd containers-quickstarts
./_test/setup.sh applier containers-quickstarts-tests pabrahamsson/containers-quickstarts feature/jenkins-agent-4.9-base
./_test/setup.sh test
```

Update Jenkins Agent base images to 4.9 + add cosign & image-mgmt tests

---

jenkins-agents/jenkins-agent-image-mgmt/Dockerfile
jenkins-agents/jenkins-agent-image-mgmt/README.md
jenkins-agents/jenkins-agent-image-mgmt/version.json

Bump skopeo to v1.5.0
Should be taken care of by CI, otherwise manually
```
./_test/setup.sh applier pabrahamsson/containers-quickstarts jenkins-agent-image-mgmt-1-5-0
./_test/setup.sh test pabrahamsson/containers-quickstarts jenkins-agent-image-mgmt-1-5-0
```

Update skopeo to 1.5.0 in jenkins-agent-image-mgmt

---

tower-ocp-custom/.openshift/templates/tower-ocp-custom-image.yml

This PR reverts the helm installation added for Tower image template,  applied in https://github.com/redhat-cop/containers-quickstarts/pull/549 , which was not needed and was applied by mistake
Removal of helm binary installation in custom Tower image template
Run the Tower image build and confirm helm is not installed during the build.

[Tower Custom Image] Revert addition of helm binary

---

jenkins-agents/jenkins-agent-ruby/Dockerfile

Ruby 2.6 is nearing [EOL (March 2022)](https://www.ruby-lang.org/en/news/2021/11/24/ruby-2-6-9-released/)
> Ruby 2.6 is now under the state of the security maintenance phase, until the end of March of 2022. After that date, maintenance of Ruby 2.6 will be ended. We recommend you start planning the migration to newer versions of Ruby, such as 3.0 or 2.7.
CI will pass

Switch to Ruby 2.7 in jenkins-agent-ruby image

---

.github/workflows/build-s2i-python-kopf-publish.yaml
.github/workflows/jenkins-agent-image-mgmt-publish.yaml
.github/workflows/jenkins-agent-python-publish.yaml
.github/workflows/rabbitmq-publish.yaml
.github/workflows/tekton-task-images-conftest-publish.yaml
.github/workflows/tekton-task-images-helm-publish.yaml
.github/workflows/ubi7-gitlab-runner-publish.yaml
.github/workflows/ubi8-asciidoctor-publish.yaml
.github/workflows/ubi8-bats-publish.yaml
.github/workflows/ubi8-git-publish.yaml
.github/workflows/ubi8-google-api-python-client-publish.yaml

Reason/concept behind this change: when building on my fork, as the actions are only active on master, I never know if my changes have worked as I normally work on a dedicated branch for that change. this change removes those filters for that reason.
also, as we push to quay, my fork needs to have quay config setup. i have this already, but 99% of people wont. so I've added ghcr in so they can run the publish
CI goes green on merge. you can see it green on my fork: https://github.com/garethahealy/containers-quickstarts/actions

added ghcr to publish ci and remove branch filtering to always publish on push

---

.applier/group_vars/seed-hosts.yml
jenkins-agents/jenkins-agent-zap/Dockerfile

It will fix the issue below
```
Pulling image centos:centos7 ...
Trying to pull docker.io/library/centos:centos7...
time="2022-03-01T23:25:13Z" level=warning msg="failed, retrying in 1s ... (1/3). Error: initializing source docker://centos:centos7: reading manifest centos7 in docker.io/library/centos: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"
time="2022-03-01T23:25:49Z" level=warning msg="failed, retrying in 2s ... (2/3). Error: initializing source docker://centos:centos7: reading manifest centos7 in docker.io/library/centos: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: …
```

FIX: Avoid Docker Hub rate limit for Zap Agent

---

jenkins-agents/jenkins-agent-cosign/Dockerfile

This PR updates jenkins-agent-cosign Dockerfile to install v1.7.2 version of cosign instead of v1.0.0
Build&Run the image with TL500 exercise

Update cosign from v1.0.0 to v1.7.2 on jenkins-agent-cosign

---

utilities/ubi8-asciidoctor/Dockerfile
utilities/ubi8-asciidoctor/version.json

Versions of dependencies updates
asciidoctor 2.0.18 -> 2.0.20
asciidoctor-pdf 2.3.4 -> 2.39
asciidoctor-diagram 2.2.3 -> 2.2.14
asciidoctor_revealjs 4.1.0 -> 5.0.1
pandoc 3.0 -> 3.1.8
ruby 3.0 -> 3.1
version of image 2.0.1 -> 2.1
Create the image.
Generate a pdf.
Compare with previous generated pdf, from previous image version.
Tested this version with older generated pdf.
pdf is generated and comparable with previous version
There are differences, but that depends on the style-sheet used by user, which is not under control of this image.

Update to current versions - housekeeping

---

.github/workflows/tekton-task-images-conftest-pr.yaml
.github/workflows/tekton-task-images-conftest-publish.yaml
.github/workflows/tekton-task-images-helm-pr.yaml
.github/workflows/tekton-task-images-helm-publish.yaml
SECURITY.md
renovate.json
tekton-task-images/conftest/VERSION
tekton-task-images/helm/Dockerfile
tekton-task-images/helm/VERSION

- added renovate to tekton images
- added default permissions for CI to be read-only, and elevated where needed - https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions

updated tekton versions to be renovated

---

.github/workflows/scorecard.yml

[scorecard](https://securityscorecards.dev/) runs checks against the repo and flags any issues, such as ci permissions. simple and easy win for a repo to improve.

added scorecard ci

---

jenkins-agents/jenkins-agent-ruby/Dockerfile

It will fix the failing CI test (missing `libyaml-devel` package) and also update to ruby 3.1 and OCP 4.14

fix: Update and fix jenkins-agent-ruby image

---

.github/workflows/tookbox-pr.yaml
.github/workflows/ubi8-bats-pr.yaml
.github/workflows/ubi8-git-pr.yaml
.github/workflows/ubi8-google-api-python-client-pr.yaml
tekton-task-images/conftest/Dockerfile
tool-box/Dockerfile
tool-box/requirements.txt
utilities/ubi8-bats/Dockerfile
utilities/ubi8-bats/test/unit.bats
utilities/ubi8-git/Dockerfile
utilities/ubi8-google-api-python-client/Dockerfile
utilities/ubi8-google-api-python-client/requirements.txt

started to clean up some of the other images, making use of hadolint and multi stage builds to cut down the images

cleanup of toolbox and utils

---

_test/kind/setup.sh
jenkins-agents/jenkins-agent-ansible/Dockerfile
jenkins-agents/jenkins-agent-gradle/Dockerfile
jenkins-agents/jenkins-agent-helm/Dockerfile
jenkins-agents/jenkins-agent-ruby/Dockerfile

moved the other remaining jenkins images to the 4.14 tag - java alternatives breaking things.

updated outstanding jenkins bases to 4.14

---

utilities/ubi8-bats/test/unit.bats

Remove the need to test hard coded versions of ubi8-bats dependencies. It is enough to test that the dependency is able to execute successfully.
CI goes :heavy_check_mark: 

fix: Remove version testing for ubi8-bats dependencies

---

jenkins-agents/jenkins-agent-ansible/Jenkinsfile.test
jenkins-agents/jenkins-agent-arachni/Jenkinsfile.test
jenkins-agents/jenkins-agent-argocd/Jenkinsfile.test
jenkins-agents/jenkins-agent-conftest/Jenkinsfile.test
jenkins-agents/jenkins-agent-cosign/Jenkinsfile.test
jenkins-agents/jenkins-agent-erlang/Jenkinsfile.test
jenkins-agents/jenkins-agent-golang/Jenkinsfile.test
jenkins-agents/jenkins-agent-graalvm/Jenkinsfile.test
jenkins-agents/jenkins-agent-gradle/Jenkinsfile.test
jenkins-agents/jenkins-agent-helm/Jenkinsfile.test
jenkins-agents/jenkins-agent-hugo/Jenkinsfile.test
jenkins-agents/jenkins-agent-image-mgmt/Jenkinsfile.test
jenkins-agents/jenkins-agent-mongodb/Jenkinsfile.test
jenkins-agents/jenkins-agent-mvn/Jenkinsfile.test
jenkins-agents/jenkins-agent-npm/Jenkinsfile.test
jenkins-agents/jenkins-agent-python/Jenkinsfile.test
jenkins-agents/jenkins-agent-ruby/Jenkinsfile.test
jenkins-agents/jenkins-agent-rust/Jenkinsfile.test

adds a safety check to the `Jenkinsfile` to make sure git is working correclty

added clone test to jenkins agents

---

jenkins-agents/jenkins-agent-npm/Dockerfile

NPM builds get below error while using this agent: 
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /home/jenkins/.npm/_cacache
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000790000:0 "/home/jenkins/.npm"
Adding the step that npm suggests in the above error

🫥 chown fix for npm error 🫥
