- s2i-java/README.md
Added a BOM for s2i-java image to resolve #8 
CC: @etsauer @raffaelespazzoli
> Updated s2i-java README to include full BOM

- quickstart-templates/rhel-templates.json
- s2i-httpd/Dockerfile
- s2i-httpd/README.md
Adding Source to Image support for a standalone Apache HTTPD web server
Execute the instructions found in the s2i-httpd README
https://trello.com/c/jMcYQV7t
/cc @etsauer @raffaelespazzoli
> s2i-httpd image

- cicd/jenkins-s2i/jenkins-s2i.yml
- cicd/jenkins-s2i/plugins.txt
- cicd/pipeline
- cicd/pipeline-basic/README.md
- cicd/pipeline-basic/generic-java-jenkins-pipeline.yml
- cicd/pipeline-basic/jws30-tomcat8-deployment.yml
- cicd/pipeline-basic/pipeline.groovy
This PR contains a sample pipeline, plus a customized s2i build for jenkins to update it to the proper version of the kubernetes plugin
Follow instructions in `cicd/pipeline-basic/README.md`
> Adding pipeline templates and required dependencies to run it

- cicd/pipeline
Moves pipeline create script to use `oc apply` and adds new project method to make the script idempotent.
`cicd/pipeline deploy myapp --image-namespace myapp-ib`
> Switching over to oc apply for creating resources

- jenkins-slaves/jenkins-slave-image-mgmt/README.md
> Fix typos in README

- mongo-statefulset/README.md
- mongo-statefulset/mongodb-statefulset-replication.yaml
Example for deploying a MongoDB replica set as a StatefulSet
Follow the steps as describe in the README
> Added MongoDB statefulset example

- s2i-jekyll/Dockerfile
- s2i-jekyll/README.md
- s2i-jekyll/s2i/assemble
- s2i-jekyll/s2i/run
Adds a builder image for generating jekyll sites
Follow README
cc: @redhat-cop/containerize-it @redhat-cop/cant-contain-this
> Adding s2i builder for jekyll

- kafka/README.md
- kafka/templates/kafka-build.json
- kafka/templates/kafka.json
- zookeeper/README.md
- zookeeper/templates/zookeeper-build.json
- zookeeper/templates/zookeeper.json
Migration of existing quickstarts from PetSets to StatefulSets to resolve #34 #35 #33
Follow the instructions on the associated README's
cc: @redhat-cop/containerize-it @raffaelespazzoli
> Migrate Petset->StatefulSet

- s2i-gows/image/Dockerfile
Fixes the dockerfile now that the README is outside of the buildcontext.
Build dockerfile.
> Removing README from dockerfile

- jenkins-slaves/jenkins-slave-ruby/Dockerfile
- jenkins-slaves/jenkins-slave-ruby/README.md
- jenkins-slaves/jenkins-slave-ruby/root/opt/app-root/.gemrc
- jenkins-slaves/jenkins-slave-ruby/root/opt/app-root/build.sh
- jenkins-slaves/jenkins-slave-ruby/root/opt/app-root/etc/puma.cfg
- jenkins-slaves/jenkins-slave-ruby/root/opt/app-root/etc/scl_enable
- jenkins-slaves/templates/jenkins-slave-ruby-template.yml
Adds a ruby jenkins slave
Run a pipeline that utilizes this image as a slave.
> Jenkins slave ruby

- jenkins-slaves/jenkins-slave-ruby/Dockerfile
> Downgrading oc client version to match 3.6.0

- jenkins-slaves/jenkins-slave-ruby/Dockerfile
Updates image to pull 3.6.0 `oc` binary from github.
Build image, run through a jenkins pipeline.
> Ruby slave fix 2

- s2i-liberty/s2i/bin/assemble-runtime
Adds support for recursively copying resources as part of the S2I build
Resolves #59 
> Added support for copying files recursively

- s2i-jekyll/Dockerfile
- s2i-jekyll/README.md
- s2i-jekyll/files/builds/docker-template.yml
- s2i-jekyll/files/builds/source-template.yml
- s2i-jekyll/files/deployments/template.yml
- s2i-jekyll/files/imagestreams/jekyll-builder/params
- s2i-jekyll/files/imagestreams/openshift-playbooks/params
- s2i-jekyll/files/imagestreams/ruby/params
- s2i-jekyll/files/imagestreams/template.yml
- s2i-jekyll/files/projects/projects.yml
- s2i-jekyll/inventory/group_vars/all.yml
- s2i-jekyll/inventory/hosts
Use openshift-applier to build and deploy s2i-jekyll
See README in PR
This will help close out [issue #56](https://github.com/redhat-cop/containers-quickstarts/issues/56)
https://trello.com/c/RFskWdVg/20-add-openshift-applier-support-to-container-quickstart-examples
> Use openshift-applier to build and deploy s2i-jekyll

- jenkins-slaves/jenkins-slave-ruby/Dockerfile
Fixes a build issue in the ruby slave
I'm not sure. 
> Adding autoconf dependency for compiling gems

- jenkins-slaves/jenkins-slave-ruby/Dockerfile
> Ruby slave automake fix

- kafka/Dockerfile
Static URL FTW
Run through the deployment and verification steps in the [README](README.md)
> Use https://archive.apache.org for kafka

- s2i-liberty/.gitignore
- s2i-liberty/README.md
- s2i-liberty/applier/inventory/group_vars/seed-hosts.yml
- s2i-liberty/applier/inventory/hosts
- s2i-liberty/applier/projects/projects.yml
- s2i-liberty/applier/templates/build.yml
- s2i-liberty/applier/templates/deployment.yml
- s2i-liberty/requirements.yml
Use openshift-applier to build and deploy an s2i image to Liberty
See README in PR
This will help close out [issue #56](https://github.com/redhat-cop/containers-quickstarts/issues/56) and [Add Openshift-applier to container-quickstart examples](https://trello.com/c/RFskWdVg/20-add-openshift-applier-support-to-container-quickstart-examples)
> Use openshift-applier to build and deploy Liberty

- jenkins-slaves/templates/jenkins-slave-image-mgmt-template.yml
> Removing namespace

- jenkins-slaves/jenkins-slave-mongodb/Dockerfile
- jenkins-slaves/jenkins-slave-mongodb/README.md
- jenkins-slaves/jenkins-slave-mongodb/mongodb-org-3.6.repo
This PR is of _yet another_ jenkins slave we've used on labs before. Thought it would be good to share it here!
```bash
cd jenkins-slaves/jenkins-slave-mongodb
docker build -t jenkins-slave-golang .
docker run --rm -i -t jenkins-slave-mongodb /bin/bash
mongo --version
mongoimport --version
```
> ADD - mongodb slave for jenkins admin of mongo

- jenkins-slaves/jenkins-slave-gradle/Dockerfile
- jenkins-slaves/jenkins-slave-gradle/README.md
Gradle build pod for J-man!
```bash
cd jenkins-slaves/jenkins-slave-gradle/
docker build -t jenkins-slave-gradle .
docker run --rm -i -t jenkins-slave-gradle /bin/bash
gradle --version
```
> ADD gradle build pod

- jenkins-slaves/jenkins-slave-arachni/Dockerfile
- jenkins-slaves/jenkins-slave-arachni/README.md
- jenkins-slaves/jenkins-slave-arachni/reporters/xml/hudson_junit-4.xsd
- jenkins-slaves/jenkins-slave-arachni/reporters/xunit.rb
Adds a new jenkins slave for web crawling a site / api and scan for vulnerabilities
Same as first two PRs, build it run it! See the readme for the commands to run in your pipeline.
> ADD - Arachni webcrawler for security scanning in pipleine

- tool-box/Dockerfile
Take care of cases when execute bit is lost when cloning. 
Tested with: oc new-app fedora:latest~https://github.com/huddlesj/containers-quickstarts.git --context-dir=tool-box/ --name=test --strategy=docker
> Updated Dockerfile

- tool-box/Dockerfile
Fix the build
```
[ tool-box ]$ docker build -t tool-box .
```
> Fixing chmod file path

- tool-box/Dockerfile
- tool-box/README.md
Add jq to the toolbox container
NA
> Adding jq to tool-box

- s2i-play/Dockerfile
- s2i-play/applier/templates/build.yml
Move from RHEL to Atomic for base image to create lighter weight images
The repo might need to be changed in the build.yml for the s2i-play project to a current repo with the necessary changes:
https://github.com/dmhumph/containers-quickstarts.git
> Update to atomic as base image

- .gitignore
- jenkins-slaves/jenkins-slave-python/Dockerfile
- jenkins-slaves/jenkins-slave-python/Dockerfile.rhel7
- jenkins-slaves/jenkins-slave-python/README.md
- jenkins-slaves/jenkins-slave-ruby/README.md
- jenkins-slaves/jenkins-slave-zap/README.md
update python slave so it includes `wheel` and `twine` which are necessary to push to pypi repos
Run the `docker` and/or `oc` commands found in the README 
> Update python slave

- jenkins-slaves/jenkins-slave-ansible/Dockerfile.rhel7
- jenkins-slaves/jenkins-slave-ansible/README.md
> Feature/jenkins slave ansible fixes #125

- s2i-play/applier/templates/build.yml
> update atomic registry url because of change at registry.access.redhat.com

- s2i-liberty/Dockerfile
- s2i-liberty/applier/templates/build.yml
- s2i-liberty/s2i/bin/assemble-runtime
upgrades the liberty build to webProfile8
run the applier
> Web profile8

- tool-box/Dockerfile
> Making a 3.10 version of tool-box

- jenkins-masters/hygieia-plugin/.openshift/templates/jenkins-s2i.yml
Templates were broken
jenkins-masters/hygieia-plugin/README.md
> Fixing the build template for the Hygieia enabled jenkins

- jenkins-masters/hygieia-plugin/.openshift/templates/jenkins-s2i.yml
> Update hygieia jenkins master build for 3.11

- hoverfly/.openshift/templates/hoverfly-deployment-template.yml
Adds command to hoverfly template that allows it to listen on all interfaces
Spin up hoverfly and verify that you can connect to it
> Add hoverfly command

- jenkins-slaves/jenkins-slave-npm/Dockerfile
- jenkins-slaves/jenkins-slave-npm/Dockerfile.rhel7
- jenkins-slaves/jenkins-slave-npm/README.md
Upgrade `jenkins-slave-npm` to nodejs 10
Follow instructions in README
> Update jenkins-slave-npm to nodejs 10, fixes #181

- jenkins-slaves/jenkins-slave-golang/Dockerfile
- jenkins-slaves/jenkins-slave-golang/Dockerfile.rhel7
Resolves #183 
Adds the SonarQube CLI scanner application to the container
`docker build -t jenkins-slave-golang .`
cc: @jacobsee @oybed
> Add SonarScanner to container image via Dockerfile

- sonarqube/.openshift/templates/sonarqube-deployment-template.yml
Helps to address https://github.com/rht-labs/labs-ci-cd/issues/19
`oc process --local -f sonarqube/.openshift/templates/sonarqube-deployment-template.yml -o yaml`
@sherl0cks @oybed @pcarney8
> Remove PostgreSQL deployment from SonarQube template

- build-s2i-executable/.applier/group_vars/seed-hosts.yml
- build-s2i-executable/.applier/hosts
- build-s2i-executable/.openshift/templates/build-s2i-executable.yml
- build-s2i-executable/Dockerfile
- build-s2i-executable/Dockerfile.rhel-minimal
- build-s2i-executable/README.md
- build-s2i-executable/requirements.yml
- build-s2i-executable/s2i/assemble
- build-s2i-executable/s2i/run
Adds a new S2I builder to run an executable artifact
Follow steps in the README
> Added new S2I executable builder

- sonarqube/.applier/group_vars/seed-hosts.yml
- sonarqube/.openshift/templates/sonarqube-deployment-template.yml
fix the params so that sonarqube will actually deploy
Run the applier in the sonarqube directory, follow the readme
> put database service name in so sonarqube will actually deploy

- .applier/group_vars/seed-hosts.yml
> seed-hosts.yml - update to use 1.11 rather then 1.3

- .travis.yml
- README.md
- TESTING.md
- build-s2i-executable/README.md
- build-s2i-gows/README.md
- build-s2i-jekyll/README.md
- build-s2i-liberty/README.md
- build-s2i-play/README.md
- deprecated/kafka/README.md
- deprecated/s2i-httpd/README.md
- deprecated/s2i-java/README.md
- deprecated/zookeeper/README.md
- gitlab-ce/README.md
- gogs/README.md
- jenkins-slaves/jenkins-slave-image-mgmt/README.md
- jenkins-slaves/jenkins-slave-mongodb/README.md
- jenkins-slaves/jenkins-slave-ruby/README.md
- linkcheck-config.json
- mongodb/README.md
- rabbitmq/README.md
- sonarqube/README.md
- tool-box/README.md
- zalenium/README.md
Fixed deadlinks in the docs due to files being moved.
Added npm package to check md links.
Currently, there are still a few deadlinks, but i am not sure how they should be fixed so have left them.
See travis output.
> Fixed dead links in docs

- sonarqube/.applier/group_vars/seed-hosts.yml
- sonarqube/.openshift/templates/sonarqube-deployment-template.yml
The webhook URL is currently hardcoded. I want to be able to set this, as it might not be that URL where my jenkins lives
Follow applier instructions.
> Added jenkins url param for webhook

- build-docker-generic/requirements.yml
- build-s2i-executable/requirements.yml
- build-s2i-gows/requirements.yml
- build-s2i-jekyll/requirements.yml
- build-s2i-liberty/requirements.yml
- build-s2i-play/requirements.yml
- gitlab-ce/requirements.yml
- gogs/requirements.yml
- jenkins-masters/hygieia-plugin/requirements.yml
- mongodb/requirements.yml
- rabbitmq/requirements.yml
- sonarqube/requirements.yml
- tool-box/requirements.yml
- zalenium/requirements.yml
Update `requirements.yml` files with latest version (`v2.1.1`) of (openshift-applier)[/redhat-cop/openshift-applier]
Follow instructions in the various READMEs on how to install the applier
> Update to v2.1.1 of the applier

- s2i-mvn-gradle/Dockerfile
- s2i-mvn-gradle/Makefile
- s2i-mvn-gradle/README.md
- s2i-mvn-gradle/s2i/bin/assemble
- s2i-mvn-gradle/s2i/bin/functions
- s2i-mvn-gradle/s2i/bin/run
- s2i-mvn-gradle/s2i/bin/save-artifacts
- s2i-mvn-gradle/s2i/bin/usage
- s2i-mvn-gradle/test/run
- s2i-mvn-gradle/test/test-app-gradle/build.gradle
- s2i-mvn-gradle/test/test-app-gradle/src/build.gradle
- s2i-mvn-gradle/test/test-app-gradle/src/main/java/net/woodmen/S2iApplication.java
- s2i-mvn-gradle/test/test-app-gradle/src/test/java/net/woodmen/S2iApplicationTests.java
- s2i-mvn-gradle/test/test-app-maven/pom.xml
- s2i-mvn-gradle/test/test-app-maven/src/main/java/hello/Application.java
- s2i-mvn-gradle/test/test-app/index.html
RHEL based s2i builder image with maven and gradle.
Fixes #41 
#
`cd s2i-mvn-gradle/`
`make test`
> Added gradle s2i builder images

- .openshift/params/ruby
- .openshift/params/test_pipelines/ruby
- .openshift/templates/jenkins-slave-generic-template.yml
- _test/setup.sh
- jenkins-slaves/jenkins-slave-ruby/Dockerfile
- jenkins-slaves/jenkins-slave-ruby/Dockerfile.rhel7
- jenkins-slaves/jenkins-slave-ruby/Jenkinsfile.test
- jenkins-slaves/jenkins-slave-ruby/root/opt/app-root/etc/scl_enable
> Update ruby slave to ruby 2.5

- CONTRIBUTING.md
- README.md
Just a quick fix for spelling, and changed "openshift" to "OpenShift" for consistency.
Just compare the diffs and make sure I didn't add additional typos, or change the context of the sentence.
> Fix small typo for consistency

- mongodb/.applier/group_vars/seed-hosts.yml
Fixing Mongo DB Project template URL
Using the README steps to create project mongo using openshift applier
> Fixing MongoDB Project Template URL in seed-hosts.yml

- build-s2i-play/.openshift/templates/build.yml
- build-s2i-play/README.md
Updates to s2i-play
Follow steps in README
> Updates to s2i play

- build-s2i-executable/README.md
- build-s2i-gows/README.md
- build-s2i-jekyll/README.md
- build-s2i-liberty/README.md
- build-s2i-play/README.md
- mongodb/README.md
- rabbitmq/README.md
Fixing some dead links throughout the repo
Click new links, verify they go to the appropriate location
> Fix dead links

- _test/common.sh
- _test/setup.sh
As per [1], when the builds fail, its hard to see whats gone wrong without direct access to jenkins. This should make it a bit easier to see why an agent failed.
- https://github.com/redhat-cop/containers-quickstarts/pull/117#issuecomment-551572412
Run prow build successfully, see no difference.
Run prow build with a 'bad' agent, see logs from jenkins.
> Added methods to download jenkins log for builds

- .openshift/templates/jenkins-slave-generic-template.j2
Resolves #286 
Attempt to build Jenkins Slaves using latest https://github.com/rht-labs/labs-ci-cd.
> Enhance Jinja template to be more backward compatible and use better defaults

- OWNERS
Add @garethahealy as reviewer to this repo
> Add Gareth as reviewer of this repo

- .applier/group_vars/seed-hosts.yml
- jenkins-slaves/jenkins-slave-helm/Dockerfile
- jenkins-slaves/jenkins-slave-helm/Jenkinsfile.test
- jenkins-slaves/jenkins-slave-helm/README.md
Adds a new Jenkins Slave for helm
Bring up a jenkins slave helm pod and check you can run helm (self tested)
> added jenkins helm slave

- TESTING.md
- _test/common.sh
- _test/setup.sh
Enhance our CI to make build logs available when tests fail
Follow TESTING.md
> Update test scripts to output failed build logs

- tool-box/Dockerfile
- tool-box/README.md
Updating helm version in the toolbox container to Helm 3
CI
> Update toolbox image to helm 3

- .applier/group_vars/seed-hosts.yml
- jenkins-slaves/jenkins-slave-arachni/Jenkinsfile.test
> Add Jenkins Arachni agent to CI

- README.md
Readme updates - nothing too crazy really :)
1) Go to this PR
2) Read the Diff (wear 👓 if needs be )
3) Merge changes 
> 🐐 README changes to reflect Labs CI/CD being depricated 🐐

- README.md
- jenkins-slaves/jenkins-slave-npm/Dockerfile
- jenkins-slaves/jenkins-slave-npm/README.md
As per discussion with @oybed and @pabrahamsson  - I've removed the `ADD` in favour of `curl` to bring in the Chrome Browser 
`docker build -t name/jenkins-slave-npm .`
> 🦆 FIX - Jenkins slave npm chrome dep 🦆

- README.md
- jenkins-slaves/jenkins-slave-argocd/Dockerfile
- jenkins-slaves/jenkins-slave-argocd/README.md
I want to add `yq` for yaml manipulation to this slave. 
In my pipeline, I'm going to edit the yaml & commit it, then kick ArgoCD. 
I don't want to have to load up a new slave just to do this small manipulation.
1. `docker build -t name/jenkins-slave-argocd .`
2. `docker run --rm -it  --entrypoint=/bin/bash name/jenkins-slave-argocd:latest`
3. Test: expected out put `test.passing == true`
```
cat << EOF | yq w - 'test.passing' true
---
test:
passing: false
EOF
```
> 🦅 ADD - yq for yaml manipulation as part of pipeline 🦅

- jenkins-slaves/jenkins-slave-argocd/Dockerfile
update argocd client 1.5.4
see existing test
> update argocd client 1.5.4

- .github/workflows/ubi7-gitlab-runner-publish.yaml
- .github/workflows/ubi8-asciidoctor-publish.yaml
- .github/workflows/ubi8-git-publish.yaml
- .github/workflows/ubi8-google-api-python-client-publish.yaml
update to publish on git tag and tag the image with "git-TAG_NAME"
I have demonstrated this working on my fork:
https://github.com/itewk/containers-quickstarts
https://quay.io/repository/itewk/ubi8-git?tab=tags
> .github/workflows/*-publish.yaml - update to publish on git tag and tag the image with "git-TAG_NAME"

- .github/workflows/ubi8-asciidoctor-pr.yaml
- utilities/ubi8-asciidoctor/Dockerfile
- utilities/ubi8-asciidoctor/version.json
addds pandoc to the asciidoctor image as it is often used in concert
the pipeline tests that pandoc is installed
> utilities/ubi8-asciidoctor - add pandoc

- rabbitmq/README.md
- rabbitmq/chart/.helmignore
- rabbitmq/chart/Chart.yaml
- rabbitmq/chart/templates/NOTES.txt
- rabbitmq/chart/templates/_helpers.tpl
- rabbitmq/chart/templates/configmap.yaml
- rabbitmq/chart/templates/deployment.yaml
- rabbitmq/chart/templates/ingress.yaml
- rabbitmq/chart/templates/rolebinding.yaml
- rabbitmq/chart/templates/service.yaml
- rabbitmq/chart/templates/serviceaccount.yaml
- rabbitmq/chart/templates/tests/test-connection.yaml
- rabbitmq/chart/values.yaml
A Helm chart for deploying RabbitMQ
Follow instructions in README
> Add Helm chart for RabbitMQ

- rabbitmq/README.md
- rabbitmq/chart/templates/configmap.yaml
- rabbitmq/chart/values.yaml
- rabbitmq/test/acceptance/_helpers.bash
- rabbitmq/test/acceptance/rabbitmq.bats
- rabbitmq/test/unit/_helpers.bash
- rabbitmq/test/unit/configmap.bats
- rabbitmq/test/unit/rolebinding.bats
- rabbitmq/test/unit/service.bats
- rabbitmq/test/unit/serviceaccount.bats
- rabbitmq/test/unit/statefulset.bats
Adds unit and acceptance tests to the RabbitMQ Helm chart, fixes #313, #321 
Follow instructions in README, future PR(s) will add CI testing (Prow or GH actions)
> Add Bats testing for RabbitMQ Helm chart

- .github/workflows/ubi8-google-api-python-client-pr.yaml
- utilities/ubi8-google-api-python-client/Dockerfile
- utilities/ubi8-google-api-python-client/README.md
- utilities/ubi8-google-api-python-client/root/usr/local/bin/upload-file-to-google-drive
- utilities/ubi8-google-api-python-client/version.json
adds upload-file-to-google-drive.py to ubi8-google-api-python-client image.
Updated github PR workflow to have a basic test that the script is there.
> upload-file-to-google-drive.py - init add

- .github/workflows/conftest.yaml
- _test/_helpers.bash
- _test/conftest.sh
Adds conftest as a github workflow action
See actions output
> Added github workflow action for conftest

- jenkins-masters/hygieia-plugin/.openshift/projects/projects.yml
> 🦄 FIX - typo 🔥

- zalenium/README.md
The docs for Zalenium suffer from some copy and paste issues so I have corrected them along with a few other cosmetic fixes
📖 👀 
> 🦄 Tidy up docs for Zalenium 🔥

- jenkins-slaves/jenkins-slave-argocd/Dockerfile
bump argocd client to latest stable version
prow will test this
> 🦩bump argocd client 🦩

- OWNERS
Currently no one from outside of the US is allowed to `approve` PRs in this repo. Seems kinda odd to me especially as some of us (ie @garethahealy and myself) are high contributors and have merge rights. This PR is to fix that (and add @tylerauerbeck to said list)
https://github.com/orgs/redhat-cop/teams/day-in-the-life-mergers/members
https://github.com/redhat-cop/containers-quickstarts/graphs/contributors
n/a
> 🦄 EMEA approvers (and Tyler) 🔥

- .openshift/templates/jenkins-pipeline-template-no-ocp-triggers.j2
> 🛎  Fix api version for ocp4 happiness 🎣

- gitlab-ce/README.md
spelling mistake in readme 
🤷  
> 🕵️‍♂️ Fix spelling mistake 👀

- README.md
Container Quickstarts or Containers Quickstarts? Either way, let's be consistent with the URL ....
> 🕵️‍♂️ Typo in the README 👀

- hoverfly/.applier/group_vars/seed-hosts.yml
- hoverfly/Dockerfile
- hoverfly/README.md
- hoverfly/requirements.yml
Jump hoverfly to a more recent version (and bump applier as it's out of date)
> 🛎  Bump some versions 🎣

- .applier/group_vars/seed-hosts.yml
Fix some version changes for ocp4 
Don't really know as Im not sure where this server is executed. I assume prow will take care of this?
> 🤯 Version fix for the slave ci 🤥

- .applier/group_vars/seed-hosts.yml
- jenkins-slaves/jenkins-slave-conftest/Dockerfile
- jenkins-slaves/jenkins-slave-conftest/Jenkinsfile.test
- jenkins-slaves/jenkins-slave-conftest/README.md
Adding tools for running conf tests in a Jenkins pipeline. Inspired by @garethahealy 's GH Action. 
build and run the image. 
> 🏏 Conftest and Bats agent  for Jenkins 🦇

- tool-box/Dockerfile
Fixes #365
build it, run it, execute helm :)
> 🦄 FIX - Helm perms 🔥

- jenkins-slaves/jenkins-slave-argocd/Dockerfile
> 🦩bump version to latest argocd-1.6.0🦩

- ubi7-gitlab-runner/README.md
Update the example commands to genericize the use case.
Add command to add gitlab helm repo
Updating the readme to clarify commands
n/a
> Fix typos and update example in README

- jenkins-slaves/jenkins-slave-ruby/Dockerfile
- jenkins-slaves/jenkins-slave-ruby/README.md
As above
Standard ruby agent tests
> Update ruby jenkins agent to ruby 2.6

- jenkins-slaves/jenkins-slave-ruby/README.md
Fix small typo in the readme format 
👓
> 👓 Fix readme formatting 👓

- jenkins-slaves/jenkins-slave-ruby/Dockerfile
- jenkins-slaves/jenkins-slave-ruby/README.md
- jenkins-slaves/jenkins-slave-ruby/root/opt/app-root/etc/scl_enable
> Update ruby jenkins agent to nodejs 12

- mongodb/.openshift/templates/configsvr.yml
- mongodb/.openshift/templates/replset.yml
Fix missing selectors in StatefulSets templates. (ansible playbook run was broken)
ansible-playbook -i .applier/hosts roles/openshift-applier/playbooks/openshift-cluster-seed.yml
> Fix missing selectors in StatefulSets

- .github/workflows/github-runner-ubi8.yaml
- github-runner-ubi8/README.md
Fix Build for GitHub runner
Replicate steps in README
> Fix Build for GitHub runner

- jenkins-agents/jenkins-agent-argocd/Dockerfile
update to latest argocd client 1.7.2
in built tests
> 🐪 updated to 1.7.2 argocd 🐪

- .applier/group_vars/seed-hosts.yml
- README.md
- jenkins-agents/jenkins-agent-graalvm/Dockerfile
- jenkins-agents/jenkins-agent-graalvm/Jenkinsfile.test
- jenkins-agents/jenkins-agent-graalvm/README.md
- jenkins-agents/jenkins-agent-graalvm/settings.xml
- jenkins-agents/jenkins-agent-graalvm/ubi.repo
Add a GraalVM Jenkins Agent
The test suite for Jenkins Agents have been updated to include tests for this Agent and will be tested by Prow.
Manual tests can be done with the following commands.
```
./_test/setup.sh applier cqci pabrahamsson/containers-quickstarts feature/jenkins-agent-graalvm
./_test/setup.sh test cqci pabrahamsson/containers-quickstarts feature/jenkins-agent-graalvm
```
> Add GraalVM Jenkins Agent

- jenkins-agents/jenkins-agent-ansible/Dockerfile
add pip pkgs openshift and kubernetes
build and run as usual
> jenkins-agent-ansible add pip pkgs openshift and kubernetes

- jenkins-agents/jenkins-agent-argocd/Dockerfile
update argocd 1.7.0, ocp base 4.6, yq 3.4.1 - all latest GA versions
Jenkinsfile.test included
> 🐠 updated to latest supported GA versions 🐠

- jenkins-agents/jenkins-agent-argocd/Dockerfile
bump to latest stable argocd 1.8.1
jenkinsfile test included
> 🦅 argocd 1.8.1 🦅

- ipa-server/.openshift/files/01-worker-sebool.yml
Ignition file version updated to 3.1.0
By applying it? :)
> ignition file version updated

- github-runner-ubi8/.openshift/templates/github-runner-ubi8-deployment.yaml
- github-runner-ubi8/Dockerfile
- github-runner-ubi8/README.md
- github-runner-ubi8/entrypoint.sh
- github-runner-ubi8/version.json
Various updates to the UBI8 GitHub Runner image
Execute steps in the README
> Updates to UBI8 GitHub Runner image

- github-runner-ubi8/Dockerfile
- github-runner-ubi8/entrypoint.sh
- github-runner-ubi8/version.json
Bugfixes and runner version bump
Follow steps in README
> Various fixes to UBI GitHub Runner

- jenkins-agents/jenkins-agent-argocd/Dockerfile
- jenkins-agents/jenkins-agent-zap/Dockerfile
bump to latest supported versions
see jenkinsfile test
> 🐝 argocd 1.8.3, yq 4.5.0 🐝

- jenkins-agents/jenkins-agent-argocd/Dockerfile
bump latest argocd 1..8.5
see Jenkinsfile test
> 🐞 bump argocd 1.8.5 🐞

- jenkins-agents/jenkins-agent-zap/Dockerfile
Resolves #456 
CI/PR build should pass
> FIX: Jenkins Zap Agent pip url update

- build-docker-generic/.applier/group_vars/seed-hosts.yml
- build-docker-generic/Dockerfile
- build-docker-generic/requirements.yml
> bumped versions and fixed source repo for build-docker-generic

- build-s2i-jekyll/.applier/group_vars/seed-hosts.yml
- build-s2i-jekyll/README.md
- build-s2i-jekyll/requirements.yml
> bumped versions and fixed docs for jekyll

- build-s2i-gows/.applier/group_vars/seed-hosts.yml
- build-s2i-gows/README.md
- build-s2i-gows/requirements.yml
> bumped versions and fixed docs for gows

- build-s2i-liberty/.applier/group_vars/seed-hosts.yml
- build-s2i-liberty/README.md
- build-s2i-liberty/requirements.yml
> bumped versions and fixed docs for liberty

- build-s2i-executable/.applier/group_vars/seed-hosts.yml
- build-s2i-executable/requirements.yml
> bumped versions for build-s2i-executable

- .github/workflows/build-s2i-python-kopf-pr.yaml
- .github/workflows/build-s2i-python-kopf-publish.yaml
- .github/workflows/github-runner-ubi8.yaml
- .github/workflows/jenkins-agent-image-mgmt-publish.yaml
- .github/workflows/jenkins-agent-python-pr.yaml
- .github/workflows/jenkins-agent-python-publish.yaml
- .github/workflows/rabbitmq-pr.yaml
- .github/workflows/rabbitmq-publish.yaml
- .github/workflows/tekton-task-images-conftest-pr.yaml
- .github/workflows/tekton-task-images-conftest-publish.yaml
- .github/workflows/tekton-task-images-helm-pr.yaml
- .github/workflows/tekton-task-images-helm-publish.yaml
- .github/workflows/ubi7-gitlab-runner-pr.yaml
- .github/workflows/ubi7-gitlab-runner-publish.yaml
- .github/workflows/ubi8-asciidoctor-pr.yaml
- .github/workflows/ubi8-asciidoctor-publish.yaml
- .github/workflows/ubi8-bats-pr.yaml
- .github/workflows/ubi8-bats-publish.yaml
- .github/workflows/ubi8-git-pr.yaml
- .github/workflows/ubi8-git-publish.yaml
- .github/workflows/ubi8-google-api-python-client-pr.yaml
- .github/workflows/ubi8-google-api-python-client-publish.yaml
Remove copy pasta `-` GH actions
> Syntax fixes for GH Actions

- .github/workflows/build-s2i-python-kopf-pr.yaml
- .github/workflows/build-s2i-python-kopf-publish.yaml
- .github/workflows/github-runner-ubi8.yaml
- .github/workflows/jenkins-agent-image-mgmt-pr.yaml
- .github/workflows/jenkins-agent-image-mgmt-publish.yaml
- .github/workflows/jenkins-agent-python-pr.yaml
- .github/workflows/jenkins-agent-python-publish.yaml
- .github/workflows/rabbitmq-pr.yaml
- .github/workflows/rabbitmq-publish.yaml
- .github/workflows/tekton-task-images-conftest-pr.yaml
- .github/workflows/tekton-task-images-conftest-publish.yaml
- .github/workflows/tekton-task-images-helm-pr.yaml
- .github/workflows/tekton-task-images-helm-publish.yaml
- .github/workflows/ubi7-gitlab-runner-pr.yaml
- .github/workflows/ubi7-gitlab-runner-publish.yaml
- .github/workflows/ubi8-asciidoctor-pr.yaml
- .github/workflows/ubi8-asciidoctor-publish.yaml
- .github/workflows/ubi8-bats-pr.yaml
- .github/workflows/ubi8-bats-publish.yaml
- .github/workflows/ubi8-git-pr.yaml
- .github/workflows/ubi8-git-publish.yaml
- .github/workflows/ubi8-google-api-python-client-pr.yaml
- .github/workflows/ubi8-google-api-python-client-publish.yaml
fixs: https://github.com/redhat-cop/containers-quickstarts/issues/474
*all* CI should jobs for PR go green
> fixed build/publish ci failing

- .github/workflows/jenkins-agent-image-mgmt-publish.yaml
https://github.com/redhat-cop/containers-quickstarts/issues/474
> Downgraded to ubuntu-18.04 for jenkins image mgt publish

- .github/workflows/tekton-task-images-conftest-publish.yaml
- .github/workflows/tekton-task-images-helm-publish.yaml
> Use more descriptive names for Tekton Task images

- jenkins-agents/jenkins-agent-hugo/Dockerfile
- jenkins-agents/jenkins-agent-hugo/Jenkinsfile.test
- jenkins-agents/jenkins-agent-hugo/README.md
Hugo static site stuff
docker build ...  / use the test script
> 🐻 ADD - hugo static site builder 🐻

- .applier/group_vars/seed-hosts.yml
Add CI testing for recently merged #501 
```bash
./_test/setup.sh applier jenkins-agent-hugo-ci pabrahamsson/containers-quickstarts jenkins-agent-hugo-ci
./_test/setup.sh test jenkins-agent-hugo-ci
```
> Add jenkins-agent-hugo to CI test

- .applier/group_vars/seed-hosts.yml
- jenkins-agents/jenkins-agent-ansible/Dockerfile
- jenkins-agents/jenkins-agent-arachni/Dockerfile
- jenkins-agents/jenkins-agent-argocd/Dockerfile
- jenkins-agents/jenkins-agent-erlang/Dockerfile
- jenkins-agents/jenkins-agent-golang/Dockerfile
- jenkins-agents/jenkins-agent-graalvm/Dockerfile
- jenkins-agents/jenkins-agent-gradle/Dockerfile
- jenkins-agents/jenkins-agent-image-mgmt/Dockerfile
- jenkins-agents/jenkins-agent-mongodb/Dockerfile
- jenkins-agents/jenkins-agent-mvn/Dockerfile
- jenkins-agents/jenkins-agent-npm/Dockerfile
- jenkins-agents/jenkins-agent-python/Dockerfile
- jenkins-agents/jenkins-agent-ruby/Dockerfile
- jenkins-agents/jenkins-agent-rust/Dockerfile
Update the jenkins-agent-base images to 4.7
```bash
./_test/setup.sh applier jenkins-agent-base-47 pabrahamsson/containers-quickstarts jenkins-agent-base-image-4.7
./_test/setup.sh test jenkins-agent-base-47
```
> Update jenkins-agent-base to 4.7

- jenkins-agents/jenkins-agent-argocd/Dockerfile
update to latest argocd 2.0.5
update to latest yq 4.11.1
see tests
> 🌶️ argocd 2.0.5 🌶️

- cert-manager-configs/.openshift/cert-manager.yml
- cert-manager-configs/.openshift/ocpv4-certs.yml
- cert-manager-configs/.openshift/route-with-cert.yml
It changes Cert-Manager CR Template version to be compatible with Cert-Manager v1.4.0
N/A
> Modification of  templates to be aligned with Cert-Manager v1.4.0

- jenkins-agents/jenkins-agent-graalvm/Dockerfile
Updates for latest versions:
- Mandrel/Graal - GRAAL_VERSION=20.3.3.0-Final
- Helm - HELM_VERSION=3.6.3
- oc OC_VERSION=4.8.2
- yq - YQ_VERSION=4.11.2
see test in this repo
> 🦩 jenkins-agent-graalvm - updates for latest version 🦩

- ipa-server/README.md
The "params" section of the README wasn't rendering correctly. This PR makes it a table. 
N/A - doc change
> Fixing up README for IPA/IdM deployment

- jenkins-agents/jenkins-agent-cosign/Dockerfile
- jenkins-agents/jenkins-agent-cosign/Jenkinsfile.test
- jenkins-agents/jenkins-agent-cosign/README.md
Extend Jenkins agent with cosign binary.
> 🐩 cosign Jenkins agent added 🐩

- tool-box/Dockerfile
- tool-box/README.md
I needed zip in the toolbox container. Updated versions of other things because i'm a swell guy.
CI should test.
> Refresh versions of toolbox image and add zip because I need it

- tool-box/Dockerfile
old version of pip was breaking build. running an upgrade to fix it.
CI
> Upgrade pipe to fix build issue

- jenkins-agents/jenkins-agent-ruby/README.md
- rabbitmq/README.md
> Fix a few README URLs

- jenkins-agents/jenkins-agent-argocd/Dockerfile
update argocd jenkins agent with latest cli tooling
see _tests
> 🌶️ argocd 2.2.3 🌶️

- tower-ocp-custom/.openshift/templates/tower-ocp-custom-image.yml
This PR adds helm binary to Tower image template.
Build the image out of template and verify helm is available
> Add helm binary to Tower image

- jenkins-agents/jenkins-agent-ruby/Dockerfile
This resolves #547 
CI will pass
> Fix jenkins-agent-ruby rubygem issue

- .github/workflows/build-s2i-python-kopf-pr.yaml
- .github/workflows/build-s2i-python-kopf-publish.yaml
- .github/workflows/conftest.yaml
- .github/workflows/github-runner-ubi8.yaml
- .github/workflows/jenkins-agent-image-mgmt-pr.yaml
- .github/workflows/jenkins-agent-image-mgmt-publish.yaml
- .github/workflows/jenkins-agent-python-pr.yaml
- .github/workflows/jenkins-agent-python-publish.yaml
- .github/workflows/rabbitmq-pr.yaml
- .github/workflows/rabbitmq-publish.yaml
- .github/workflows/tekton-task-images-conftest-pr.yaml
- .github/workflows/tekton-task-images-conftest-publish.yaml
- .github/workflows/tekton-task-images-helm-pr.yaml
- .github/workflows/tekton-task-images-helm-publish.yaml
- .github/workflows/ubi7-gitlab-runner-pr.yaml
- .github/workflows/ubi7-gitlab-runner-publish.yaml
- .github/workflows/ubi8-bats-pr.yaml
- .github/workflows/ubi8-bats-publish.yaml
- .github/workflows/ubi8-git-pr.yaml
- .github/workflows/ubi8-git-publish.yaml
- .github/workflows/ubi8-google-api-python-client-pr.yaml
- .github/workflows/ubi8-google-api-python-client-publish.yaml
updated ubuntu based to latest
CI stays green
> updated to ubuntu-latest

- .github/workflows/ubi8-asciidoctor-pr.yaml
- .github/workflows/ubi8-asciidoctor-publish.yaml
- utilities/ubi8-asciidoctor/Dockerfile
- utilities/ubi8-asciidoctor/version.json
fixs: https://github.com/redhat-cop/containers-quickstarts/issues/555
CI goes green / docker build works
> upgraded to ruby 2.7 for ascidoctor

- s2i-mvn-gradle/Dockerfile
fixes: https://github.com/redhat-cop/containers-quickstarts/issues/561
> updated base and mvn cdn url to fix build

- hygieia/Dockerfile
fixes: https://github.com/redhat-cop/containers-quickstarts/issues/560
> updated base image to fix yum failure on build

- sonarqube/Dockerfile
fixes: https://github.com/redhat-cop/containers-quickstarts/issues/562
> fixed curl missing

- .github/workflows/github-runner-ubi8-pr.yaml
- .github/workflows/github-runner-ubi8-publish.yaml
splits the single action file into PR and publish to follow the same as the others in this repo
green CI
> split gitlab runner into 2 files

- .openshift/templates/jenkins-pipeline-template-no-ocp-triggers.j2
> added annotation to call out that jenkinsPipelineStrategy deprecated

- utilities/ubi8-asciidoctor/Dockerfile
add the asciidcotor-reducer gem which replaces the old asciidoctor-coaleser script.
> ubi8-asciidcotor - add asciidcotor-reducer gem

- .github/workflows/jenkins-agent-ansible-pr.yaml
- .github/workflows/jenkins-agent-arachni-pr.yaml
- .github/workflows/jenkins-agent-argocd-pr.yaml
- .github/workflows/jenkins-agent-conftest-pr.yaml
- .github/workflows/jenkins-agent-cosign-pr.yaml
- .github/workflows/jenkins-agent-erlang-pr.yaml
- .github/workflows/jenkins-agent-golang-pr.yaml
- .github/workflows/jenkins-agent-graalvm-pr.yaml
- .github/workflows/jenkins-agent-gradle-pr.yaml
- .github/workflows/jenkins-agent-helm-pr.yaml
- .github/workflows/jenkins-agent-hugo-pr.yaml
- .github/workflows/jenkins-agent-mongodb-pr.yaml
- .github/workflows/jenkins-agent-mvn-pr.yaml
- .github/workflows/jenkins-agent-npm-pr.yaml
- .github/workflows/jenkins-agent-ruby-pr.yaml
- .github/workflows/jenkins-agent-rust-pr.yaml
- .github/workflows/jenkins-agent-zap-pr.yaml
starts to answer the below in its most basic form - build the containers
- https://github.com/redhat-cop/containers-quickstarts/issues/553
CI runs. this PR isn't to fix any agents that fail.
> added build ci for jenkins agents

- jenkins-agents/jenkins-agent-npm/Dockerfile
> Update Dockerfile to use Node v16

- tower-ocp-custom/.openshift/templates/tower-ocp-custom-image.yml
> Adding python3 venv to Ansible Tower image

- cert-manager-configs/.openshift/cert-manager.yml
- cert-manager-configs/templates/ClusterIssuer.yaml
This PR add an optional Hosted Zone ID parameter to ClusterIssuer template on Cert-Manager configuration 
Deploy ClusterIssuer on Openshift running Cert-Manager
> WIP: Add optional Hosted Zone ID parameter to ClusterIssuer template

- jenkins-agents/jenkins-agent-zap/Dockerfile
This is an attempt to fix #587 
CI jobs goes green and someone familiar with the image is able to test it.
> fix: Add updated and supported Webswing to jenkins-agent-zap

- jenkins-agents/jenkins-agent-zap/Dockerfile
This PR changes the JDK version from 1.8.0 to 11 on jenkins-agent-zap 
Build image and test against recent version of Jenkins
> Update java on jenkins-agent-zap

- .github/workflows/ubi8-asciidoctor-pr.yaml
- .github/workflows/ubi8-asciidoctor-publish.yaml
- utilities/ubi8-asciidoctor/Dockerfile
Added multiarch to ubi8-asciidoctor image
> Added multiarch to ubi8-asciidoctor

- tool-box/Dockerfile
- tool-box/README.md
Updated versions of these tools:
- OC cli
- ODO
- Ansible
- helm
- tekton
Added the following new tools:
- iputils (ping, tracepath, etc.)
- procps-ng (watch, etc.)
- ROSA cli
- AWS cli
> Update tool-box image with latest versions + new tools

- .gitignore
- jenkins-agents/jenkins-agent-cosign/Dockerfile
update cosign to v2.0.2
podman build
> 🦒 cosign 2.0.2 🦒

- README.md
Doc review:
- updating links to avoid relying on GitHub redirects
- cleanup typos
- move no longer maintained content as the last entry
No tests needed
> fix typos and update links

- .github/workflows/conftest.yaml
> Fixing ci due to branch name change

- .github/workflows/build-s2i-python-kopf-pr.yaml
- .github/workflows/build-s2i-python-kopf-publish.yaml
$subject - https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
> added default perms for ci on kopf

- .github/workflows/ubi8-asciidoctor-pr.yaml
- .github/workflows/ubi8-asciidoctor-publish.yaml
- .github/workflows/ubi8-bats-pr.yaml
- .github/workflows/ubi8-bats-publish.yaml
- .github/workflows/ubi8-git-pr.yaml
- .github/workflows/ubi8-git-publish.yaml
- .github/workflows/ubi8-google-api-python-client-pr.yaml
- .github/workflows/ubi8-google-api-python-client-publish.yaml
$subject - https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
> added default perms for ci on utilities

- .github/workflows/jenkins-agent-ansible-pr.yaml
- .github/workflows/jenkins-agent-arachni-pr.yaml
- .github/workflows/jenkins-agent-argocd-pr.yaml
- .github/workflows/jenkins-agent-ci-pr.yaml
- .github/workflows/jenkins-agent-conftest-pr.yaml
- .github/workflows/jenkins-agent-cosign-pr.yaml
- .github/workflows/jenkins-agent-erlang-pr.yaml
- .github/workflows/jenkins-agent-golang-pr.yaml
- .github/workflows/jenkins-agent-graalvm-pr.yaml
- .github/workflows/jenkins-agent-gradle-pr.yaml
- .github/workflows/jenkins-agent-helm-pr.yaml
- .github/workflows/jenkins-agent-hugo-pr.yaml
- .github/workflows/jenkins-agent-image-mgmt-pr.yaml
- .github/workflows/jenkins-agent-image-mgmt-publish.yaml
- .github/workflows/jenkins-agent-mongodb-pr.yaml
- .github/workflows/jenkins-agent-mvn-pr.yaml
- .github/workflows/jenkins-agent-npm-pr.yaml
- .github/workflows/jenkins-agent-python-pr.yaml
- .github/workflows/jenkins-agent-python-publish.yaml
- .github/workflows/jenkins-agent-ruby-pr.yaml
- .github/workflows/jenkins-agent-rust-pr.yaml
- .github/workflows/jenkins-agent-zap-pr.yaml
- _test/kind/setup.sh
trying to fix jenkins tests...
> bumped jenkins version and ci permissions

- .github/workflows/build-s2i-python-kopf-publish.yaml
- .github/workflows/jenkins-agent-image-mgmt-publish.yaml
- .github/workflows/jenkins-agent-python-publish.yaml
- .github/workflows/tekton-task-images-conftest-publish.yaml
- .github/workflows/tekton-task-images-helm-publish.yaml
- .github/workflows/toolbox-publish.yaml
- .github/workflows/ubi8-asciidoctor-publish.yaml
- .github/workflows/ubi8-bats-publish.yaml
- .github/workflows/ubi8-git-publish.yaml
- .github/workflows/ubi8-google-api-python-client-publish.yaml
think this should fix renovate pushing on PRs
> added exclude for push when its renovate

- .github/workflows/tekton-task-images-conftest-pr.yaml
- .github/workflows/tekton-task-images-helm-pr.yaml
- tekton-task-images/conftest/Dockerfile
- tekton-task-images/helm/Dockerfile
> Added hadolint and cleanup tekton images

- _test/kind/jenkins-values.yaml
- _test/kind/setup.sh
- jenkins-agents/jenkins-agent-npm/Jenkinsfile.test
- renovate.json
make sure https://github.com/redhat-cop/containers-quickstarts/pull/748 is fixed
> added npm install test

- tool-box/Dockerfile
Adding various networking tools, including:
- ping
- tracepath
- traceroute
Run the tool-box container and use one of the tools listed above.
> Add various net tools to tool-box
